### ISSUE TITLE
C# generated code error in nested types

### ISSUE THREAD

**Issue by superamir** [google/protobuf#563] opened 2015-07-01 08:38 UTC
When generating nested types (message, enum, etc') the generated code does not compile, it is missing the "Types" identifier before the type.
this only happen when you have a nested type inside a nested type , e.g.:
message type1 {
   message type2 {
        message type3 {      
         }
   }
} 

type3 will be missing the Types identifier in all places in the code (except when defined).
of course all this is done using  syntax = "proto2";"

**Comment by jskeet** [comment] 2015-07-03 11:47
Duplicate of #307. Fixed in the csharp-experimental branch.

**Closed by jskeet** 2015-07-03 11:47 UTC
