### ISSUE TITLE
c# support for .Net 3.0

### ISSUE THREAD

**Issue by Extrawurst** [google/protobuf#902] opened 2015-10-22 15:11 UTC
Is it (will it be) possible to use with C# .Net 3.0 ? This is the version of C# that is supported by Unity and using protobuf there is a pretty big usecase.

**Comment by jtattermusch** [comment] 2015-10-22 19:44
https://github.com/google/protobuf/issues/644

**Comment by jskeet** [comment] 2016-01-28 09:22
Yup, this is a dupe of #644. Will close this one to leave all discussion there.

**Closed by jskeet** 2016-01-28 09:22 UTC
Labels: c#

**Comment by ChenFengPa** [comment] 2016-08-02 03:43
in this github have a batch surport ,net3.5 in unity https://github.com/bitcraftCoLtd/protobuf3-for-unity
