### ISSUE TITLE
int32 field is not defined when set to zero unless wrapped in oneof statement

### ISSUE THREAD

**Issue by christian-storm** [google/protobuf#1655] opened 2016-06-08 02:03 UTC
Using protobuf release 3.0.0b3 and b2.

I built up this example to demonstrate.

document_markup.proto
```
syntax = "proto3";

message Corpus {
  message Document {
    message TextLabel {
      string label = 1;
      repeated TextSpan text_span = 2;
    }
    repeated TextLabel text_label = 2;
    message TextSpan {
      oneof test_oneof {
        int32 start_char_offset = 1;
      }
      int32 end_char_offset = 2;
    }
  }
  repeated Document document = 1;
}

```

When I run this python code:
```
#!/env/python

import document_markup_pb2

corpus = document_markup_pb2.Corpus()
doc = corpus.document.add()
text_label = doc.text_label.add()
text_label.label = u'foo'
text_span = text_label.text_span.add()
text_span.start_char_offset = 0
text_span.end_char_offset = 0

print text_span.start_char_offset
print text_span.end_char_offset
print text_label
```
I get:
0
0
label: "foo"
text_span {
  start_char_offset: 0
}
so it is getting set but not staying set unless I use some oneof magic.

It seems things are going south python_message.py field_setter(self, new_value) when new_value = 0 
In particular this if statement is true when new_value is zero:
if clear_when_set_to_default and not new_value:
      self._fields.pop(field, None)

After having read [this](https://github.com/google/protobuf/issues/1606) and "Also note that if a scalar message field is set to its default, the value will not be serialized on the wire." in the defaults documentation this may actually be desired behavior.  However, this is confusing as all get out.  Seemingly defaults are there to be relied on?  However, in my case the field was actually being set to zero (not defaulting to zero) but acts as if that field was never set!  Oh man, I chased my tail on this one.

**Comment by xfxyjwf** [comment] 2016-06-22 22:52
duplicate of https://github.com/google/protobuf/issues/1606

**Closed by xfxyjwf** 2016-06-22 22:52 UTC
Labels: duplicate
