### ISSUE TITLE
Grammar doesn't match tests: field name cannot start with underscore

### ISSUE THREAD

**Issue by stepancheg** [google/protobuf#4565] opened 2018-04-26 18:50 UTC
[Unittest](https://github.com/google/protobuf/blob/a21f225824e994ebd35e8447382ea4e0cd165b3c/src/google/protobuf/test_messages_proto3.proto#L202) contains field:

```
 int32 _field_name3 = 403;
```

[Grammar] doesn't allow field names to start with an underscore.

**Comment by dsnet** [comment] 2018-04-26 20:35
Duplicate of #4554.

**Comment by acozzette** [comment] 2018-04-30 20:42
Let me close this issue since that duplicate was opened first, and then we can move the discussion over there to #4554.

**Closed by acozzette** 2018-04-30 20:42 UTC
