### ISSUE TITLE
Segmentation Fault in SyncMapWithRepeatedField

### ISSUE THREAD

**Issue by cancan101** [google/protobuf#2863] opened 2017-03-16 14:57 UTC
```
(lldb) bt
* thread #1: tid = 0x1f7df3f, 0x0000000105cb720a _pywrap_tensorflow.so`google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const + 10, stop reason = EXC_BAD_ACCESS (code=1, address=0x7fff0000006d)
    frame #0: 0x0000000105cb720a _pywrap_tensorflow.so`google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const + 10
  * frame #1: 0x00000001059bef79 _pywrap_tensorflow.so`tensorflow::AttrSlice::AttrSlice(tensorflow::NodeDef const&) + 25
```
```
frame #0: 0x0000000105cb720a _pywrap_tensorflow.so`google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const + 10
_pywrap_tensorflow.so`google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField:
->  0x105cb720a <+10>: movl   0x30(%rbx), %r14d
    0x105cb720e <+14>: callq  0x105d4b48e               ; symbol stub for: OSMemoryBarrier
    0x105cb7213 <+19>: cmpl   $0x1, %r14d
    0x105cb7217 <+23>: jne    0x105cb724e               ; <+78>
```
This is caused by calling the following in a Tensorflow shapeinference function:
```c++
Status s = c->GetAttr("data_format", &data_format);
```

**Comment by haberman** [comment] 2017-03-16 16:42
Are there multiple threads accessing the protobuf? Is the crash fully reproducible/deterministic?

**Comment by cancan101** [comment] 2017-03-16 16:49
It is reproducible, see linked TF issue: https://github.com/tensorflow/tensorflow/issues/8473

**Comment by skye** [comment] 2017-03-21 20:59
@haberman this is probably on TensorFlow's end. I'm gonna work on repro and diagnosing.

**Comment by merlin82** [comment] 2017-08-02 11:46
does  it fix?

**Comment by pherl** [comment] 2017-12-11 20:35
We are closing open issues. Feel free to send PRs and reopen if you'd like to follow up on the issue.

**Closed** 2017-12-11 21:07 UTC
Labels: to close

**Comment by prem-nuro** [comment] 2020-06-02 00:14
Was this ever root caused?

**Comment by xiandong79** [comment] 2020-11-16 09:52
does this solved?
it is related to https://github.com/tensorflow/tensorflow/issues/44899
