### ISSUE TITLE
Generated Java source should be annotated with @Generated

### ISSUE THREAD

**Issue by dimo414** [google/protobuf#2513] opened 2016-12-16 18:18 UTC
Generated Java source code should be annotated with [`@Generated`](https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html) to aid static analysis and tooling. For example [Error-Prone will ignore errors in `@Generated` code](https://github.com/google/error-prone/issues/329).

As a workaround presently I have a pre-compilation step that adds the annotation manually, but ideally the protoc compiler would do this for me.

    
    <replaceregexp match="public(.*) class" replace="@javax.annotation.Generated(&quot;protoc&quot;) \0">
      <fileset dir="${proto.src}" includes="**/*.java" />
    </replaceregexp>

**Comment by madrob** [comment] 2017-07-06 21:54
Duplicate of #42 ?

**Closed** 2017-12-11 21:07 UTC
Labels: enhancement, java, to close
