### ISSUE TITLE
C++ Protocol buffer  error

### ISSUE THREAD

**Issue by lulinlin2015** [google/protobuf#514] opened 2015-06-19 04:01 UTC
I use the PB in C++，I has a problems.The error is “0x00824edf (DASS_FloodSimulation.dll)  has an unhandled exception: 0xC0000005: It occurs access violation  reading  position 0xbaadf015”,
the code :
	bool CFloodSimulationDEM_PB::getResultDepth(string sresult)
	{ 
		FloodSim::SimResultDepth simresultdp;
		simresultdp.ParseFromString(sresult);
		msgInResultDepth="";
        	int sizedp=simresultdp.simdepth().size();
        	for (int l=0;l<simResultPts.size();l++)
		{
			FloodSim::SimResultDepth::SimDepth sdepth=simresultdp.simdepth(l);	
			simResultPts[l].simdata=sdepth.pointdepth();
		}
		cout<<sizedp<<endl;
		return true;
	}

the definition in the .proto file is:

message SimResultDepth
{
message SimDepth{
  required float pointDepth=1;
  }
  repeated SimDepth simdepth=1;
}

the error stopped at the code line in picture (the yellow arrow line) ,the error information is posted above:

![probuf](https://cloud.githubusercontent.com/assets/12961483/8246990/edf1f990-167a-11e5-883e-72e024ed6ad1.png)

I think the code "simresultdp.ParseFromString(sresult);" may be the wrong code,but I don't konw why.
Help! Thank you all !

**Comment by xfxyjwf** [comment] 2015-06-19 08:14
Sorry @lulinlin2015 , but your post doesn't really have enough information for us to help you here.

**Comment by lulinlin2015** [comment] 2015-06-19 12:48
I have updated my questions,and it's about Protocol Buffer .Please help!

**Comment by xfxyjwf** [comment] 2015-06-30 06:36
I don't think there is a protobuf specific problem here. What you met seems to be common C++ programming errors. I highly suspect it's caused by an out-of-band array index.

I'm closing this because this issue tracker is not a discussion forum for such problems.

**Closed by xfxyjwf** 2015-06-30 06:36 UTC

**Comment by lulinlin2015** [comment] 2015-06-30 09:27
yes.It's C++ errors.
