### ISSUE TITLE
Allow jspb.Message.GENERATE_FROM_OBJECT to be configured externally

### ISSUE THREAD

**Issue by jonnyreeves** [google/protobuf#3558] opened 2017-08-23 20:43 UTC
The [`jspb.Message.GENERATE_FROM_OBJECT` flag](https://github.com/google/protobuf/blob/master/js/message.js#L189) is used to control the generation of the `fromObject()` method in the JavaScript compiler.  

IMHO the `fromObject()` method provides a friendlier API for JavaScript developers and I would like to be able to enable this in my project; however this feature is gated behind the [`testonly` flag](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/js/js_generator.h#L78).

I would like to change this so `fromObject` generation can be enabled independently of the other features gated behind the `testonly` flag.

Would a PR that enables this functionality be welcome / be considered for landing?

**Comment by jonny-improbable** [comment] 2017-08-24 11:06
Note this is a dupe of #1591.

**Closed** 2017-12-11 21:07 UTC
Labels: javascript, to close
