### ISSUE TITLE
Travis build failing for Objective C

### ISSUE THREAD

**Issue by pgrosu** [google/protobuf#1242] opened 2016-02-16 08:43 UTC
Jon (@jskeet) initially noticed that in PR #1239 that the Objective C Travis build was failing.  The original raw log can be downloaded from here:

[Travis Objective C Build log](https://www.dropbox.com/s/3h42r9yb6k6chbp/Objective_C_log.txt?dl=1)

By following through the log, I tried to replicate it locally on a Mac, and got the following results:

[Local Mac Build log](https://www.dropbox.com/s/aft4crfg72nd9w2/Local_Mac_Objective_C_Build.txt?dl=1)

Below is a brief summary regarding each system:

In Travis
---------

It seems to crash when `platform=iOS Simulator,name=iPad 2,OS=8.1` under `xctool`:

```Bash
++internal_xctool_debug_and_release -project objectivec/ProtocolBuffers_iOS.xcodeproj -scheme ProtocolBuffers -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPad 2,OS=8.1' run-tests

++xctool -configuration Debug -project objectivec/ProtocolBuffers_iOS.xcodeproj -scheme ProtocolBuffers -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPad 2,OS=8.1' run-tests
```
Which causes the following crash:
```
      -[UtilitiesTests testTextFormatExtra]

[2m2016-02-15 18:06:37.822 iOSTestHarness[19428:34184] warning: 'TestAllTypes.defaultString = nil;' is not clearly defined for fields with default values. Please use 'TestAllTypes.defaultString = @""' if you want to set it to empty, or call 'TestAllTypes.hasDefaultString = NO' to reset it to it's default value of 'hello'. Defaulting to resetting default value.

[2m2016-02-15 18:06:37.822 iOSTestHarness[19428:34184] warning: 'TestAllTypes.defaultBytes = nil;' is not clearly defined for fields with default values. Please use 'TestAllTypes.defaultBytes = GPBEmptyNSData()' if you want to set it to empty, or call 'TestAllTypes.hasDefaultBytes = NO' to reset it to it's default value of '<776f726c 64>'. Defaulting to resetting default value.

Test crashed while running.
```

On a local Mac
--------------

The tests seem to succeed, though version `8.1` for the `iPhone 4s` is not considered valid, as noted in the snippet below:

```Bash
** BUILD-TESTS SUCCEEDED ** (351620 ms)

++ IOS_DESTINATIONS=("platform=iOS Simulator,name=iPhone 4s,OS=8.1" "platform=iOS Simulator,name=iPhone 6,OS=9.1" "platform=iOS Simulator,name=iPad 2,OS=8.1" "platform=iOS Simulator,name=iPad Air,OS=9.1")
++ for i in '"${IOS_DESTINATIONS[@]}"'
++ internal_xctool_debug_and_release -project objectivec/ProtocolBuffers_iOS.xcodeproj -scheme ProtocolBuffers -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 4s,OS=8.1' run-tests
++ xctool -configuration Debug -project objectivec/ProtocolBuffers_iOS.xcodeproj -scheme ProtocolBuffers -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 4s,OS=8.1' run-tests
ERROR: '8.1' isn't a valid iOS version. The valid iOS versions are: (
    "9.2",
    "9.1",
    "2.1"
).


$
```

I would be happy to help out with troubleshooting this.

Thank you,
Paul

**Comment by thomasvl** [comment] 2016-02-16 15:28
Closing as a duplicate of #1232

**Closed by thomasvl** 2016-02-16 15:28 UTC
Labels: objective-c

**Comment by thomasvl** [comment] 2016-02-16 15:33
ps - as far as what simulator configs are valid, you have to check the travis page: https://docs.travis-ci.com/user/languages/objective-c

You local Xcode install might not create all of those, so to match their setup you have to go into the Xcode UI can create the simulator setup.
