### ISSUE TITLE
Cpp: Characteristic of IsInitialized() doesn't match with documentation

### ISSUE THREAD

**Issue by willdzeng** [google/protobuf#2885] opened 2017-03-21 00:38 UTC
In the documentation it says:

> bool IsInitialized() const; : checks if all the required fields have been set.

But if we just have a empty initialization, e.g.:

``` cpp
int main(int argc, char *argv[]) {
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  tutorial::Person p;
  p.Clear();
  if (p.IsInitialized()) {
    std::cout << "Initialized" << std::endl;
  } else {
    std::cout << "Not Initialized" << std::endl;
  }
  return 0;
}
```
```
$ ./test_protobuf_initialize 
Initialized
```
It still stays Initialized, I feel like this doesn't match the documentation. 
or is there a function to check if a proto is set or not?

**Comment by acozzette** [comment] 2017-03-21 15:39
It looks like this is working as intended, because `IsInitialized()` only checks required fields. Required fields are actually largely discouraged and do not even exist in proto3. If you want to check that every field (include ones that are not required) is set, there is no simple way to do that, though with a little bit of work you could probably use the reflection API to do this. Let me close this issue but feel free to reopen it if you have any more questions.

**Closed by acozzette** 2017-03-21 15:39 UTC
