### ISSUE TITLE
Cannot build any version in specific environment

### ISSUE THREAD

**Issue by vgoldring** [google/protobuf#492] opened 2015-06-12 12:43 UTC
Hi, I tried to build version 2.6.1 and 3.0.0 alpha 2 Linux in C++ using:
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15) , g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
and the same error seems to prevent installation from generating the Makefile, so later make returns:
make: **\* No targets specified and no makefile found.  Stop.
./configure output shows these strange missing features of C++ environment, that frankly are hard to believe:

checking for working memcmp... no
checking for working strtod... no
checking for pow... no
checking for pow in -lm... no
configure: WARNING: cannot find library containing definition of pow
checking for ftruncate... no
checking for memset... no
checking for mkdir... no
checking for strchr... no
checking for strerror... no
checking for strtol... no
checking zlib version... headers missing or too old (requires 1.2.0.4)
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking whether to check for GCC pthread/shared inconsistencies... yes
checking whether -pthread is sufficient with -shared... yes
checking whether what we have so far is sufficient with -nostdlib... no
checking whether -lpthread saves the day... yes
checking the location of hash_map... <tr1/unordered_map>
checking for library containing sched_yield... no
configure: error: in `/root/source/protobuf-2.6.1':
configure: error: sched_yield was not found on your system
See`config.log' for more details.

About zlib missing headers, yum reports:
Package zlib-1.2.3-29.el6.x86_64 already installed and latest version
which means the installation is not found by ./configure script.

But sched_yield seems to be the final blow.

Can someone please help me understand and/or fix this?

Thank you.

**Comment by bhack** [comment] 2015-06-30 08:32
:+1: I got the same problem compiling with NDK.

**Comment by nothingcosmos** [comment] 2015-07-11 10:58
I also have the same problem occurs in ubuntu14, it was resolved.
Cause is that I had to remove the installed GCC manually in "/usr/local".
GCC libraries have been left, I was resolved after delete them.

If there is experience , please try.

**Comment by bitcreditscc** [comment] 2015-08-21 09:21
Yup, same issue with NDK

**Comment by fwsGonzo** [comment] 2015-10-23 13:41
I have the same issue trying to compile with clang++-3.6 and -stdlib=libc++, for some reason

.... why does it have to be so hard to cross compile this thing.. and why does it even care that sched_yield exists? :(

**Comment by edkimmel** [comment] 2016-03-22 01:00
Any update on this? Same problem with ndk 11

**Comment by jakirkham** [comment] 2016-03-29 19:33
Seeing this with Mac OS 10.9 and XCode 5.0.2.

    $ clang --version
    Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
    Target: x86_64-apple-darwin13.4.0
    Thread model: posix

**Comment by scaidermern** [comment] 2016-05-13 08:45
Got the same problem on Debian testing today trying to compile protobuf 2.6.1. It seems like there is some weird fuckup inside the configure script (additionally to the usual fuckup commonly found in these scripts). My /usr/bin/gcc and /usr/bin/g++ are linked to gcc-5 and g++-5 respectively. Nevertheless the configure script decides to go with gcc-4.9 for whatever reason. It builds some C test cases which succeed. Then it continues with C++ tests and decides to use g++-4.9. But g++-4.9 is *not* installed on my system. g++-4.7 and g++-5 are. Anyway, installing g++-4.9 solves the problem.

[config.log](https://github.com/google/protobuf/files/262837/config.log.txt) attached. The day this autotools shit dies I will throw a big party.

**Comment by Evanok** [comment] 2016-10-13 09:35
Need to cross compile protobuf with buildroot on arm target. Same issues. Tested with v2.6.1 & v3.0.0.
No solution ?

**Comment by Gerjo** [comment] 2016-12-02 13:01
> configure: error: in '/home/gerjo/protobuf':
 configure: error: sched_yield was not found on your system
 See `config.log' for more details

On my system this error was fixed by running `./configure CXX=g++-4.7`. Presumably this is caused by configure literally using the `g++` command which isn't always defined or pointing to the compiler you'd like to use. It my case it didn't exist, so manually specifying the compiler worked.

**Comment by razvanm** [comment] 2017-01-05 19:05
I also hit a `sched_yield was not found on your system` error. In my case (an Ubuntu 16.04) the configure for protobuf was trying to use `c++`. Symlinking the `c++` to `g++` fixed the problem in my case.

**Comment by mateuszolszowy1991** [comment] 2017-01-14 08:36
You need to install gcc-c++. That should solve problem.

**Closed** 2017-03-09 01:19 UTC
Labels: c++, packaging & distribution

**Comment by hypnosis-i2p** [comment] 2017-06-26 02:56
Setting sysroot at CPPFLAGS helped me:
```
export SYSROOT=$NDK_ROOT/platforms/android-9/arch-arm
export CPPFLAGS="--sysroot=$SYSROOT"
./configure options
```

**Comment by mkorunoski** [comment] 2018-10-22 13:40
I was trying to cross compile it (x86_64 Ubuntu to arm64) and had the same problem. Installing both gcc-aarch64-linux-gnu and g++-aarch64-linux-gnu seems to resolve the problem. Don't rely on build-essentials to much.

**Comment by Aitinkle** [comment] 2019-12-20 04:10
Thanks a lot. I have fixed the problem after I saw this issue.
