### ISSUE TITLE
Where is com.google.protobuf.nano.android

### ISSUE THREAD

**Issue by b2b2244424** [google/protobuf#1308] opened 2016-03-08 07:36 UTC
I use protoc to generate nano file.But I didn't find the  com.google.protobuf.nano.android.ParcelableExtendableMessageNano.Can you tell me where is it?

**Comment by haberman** [comment] 2016-03-22 19:10
@pherl do you know the answer to this?

**Comment by xfxyjwf** [comment] 2016-06-01 17:39
This is a duplicate of https://github.com/google/protobuf/issues/956

**Closed by xfxyjwf** 2016-06-01 17:39 UTC
Labels: javanano
