### ISSUE TITLE
Repeated field documentation is unclear about ownership semantics

### ISSUE THREAD

**Issue by adeschamps** [google/protobuf#2893] opened 2017-03-21 20:18 UTC
If I have a repeated field, `foo`, and access it via the `foo()` or `mutable_foo()` methods, I get a `RepeatedPtrField`. The documentation on the _C++ Generated Code_ page (In the _Repeated Embedded Message Fields_ section) does not make it clear that `RepeatedPtrField` owns the pointers to its elements.

Suppose I want to iterate over a repeated field and store pointers to some of its elements in the vector `interesting_things`. In the first case, the vector will contain dangling pointers because the `RepeatedPtrField` has gone out of scope, wheras the second case is fine.

```C++
// Iterate over `RepeatedPtrField`
for (auto element : msg.mutable_collection()) {
  auto* ptr = &element;
  if (is_interesting(ptr))
    interesting_things.push_back(ptr);
}

for (auto* ptr : interesting_things) {
  std::cout << ptr->DebugString(); // WILL CRASH
}
```

```C++
// Iterate by index
auto num_elements = msg.collection_size();
for (int i = 0; i != num_elements; ++i) {
  auto* ptr = msg.collection(i);
  if (is_interesting(ptr))
    interesting_things.push_back(ptr);
}

for (auto* ptr : interesting_things) {
  std::cout << ptr->DebugString(); // THIS IS FINE
}
```

The [`repeated_field.h` documentation](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.repeated_field) says that `RepeatedPtrField` manages ownership of its pointers, but I think this should be made more clear in the _Generated Code_ documentation.

**Comment by xfxyjwf** [comment] 2017-03-21 22:05
I think the repeated_field.h documentation is already clear enough. It's not generated code, so it doesn't make sense to me to document the ownership semantics of RepeatedPtrField in the generated API doc.

And for your first code example, the problem is not that RepeatedPtrField has gone out of scope. The actual problem is that you are copying all elements to stack and storing pointers to the soon to be deleted stack objects. You should be writing this instead:
```cpp
// Iterate over `RepeatedPtrField`
for (auto& element : *msg.mutable_collection()) {
  auto* ptr = &element;
  if (is_interesting(ptr))
    interesting_things.push_back(ptr);
}

for (auto* ptr : interesting_things) {
  std::cout << ptr->DebugString();
}
```
Note that "&" after "auto" and the "*" before "msg.mutable_connection()".

**Closed by xfxyjwf** 2017-03-21 22:05 UTC
