### ISSUE TITLE
python release v3.0.0b2.post1 breaks gcloud-python

### ISSUE THREAD

**Issue by xfxyjwf** [google/protobuf#1294] opened 2016-03-04 22:06 UTC
See: https://github.com/GoogleCloudPlatform/gcloud-python/issues/1570

Probable cause: https://github.com/google/protobuf/commit/786f80fe6632902be74f90a577d75e8641494abd#commitcomment-16491845

@haberman @silviulica

**Comment by haberman** [comment] 2016-03-05 00:21
Closing in favor of: https://github.com/google/protobuf/issues/1296

**Closed by haberman** 2016-03-05 00:21 UTC
Labels: bug, python

**Comment by xfxyjwf** [comment] 2016-03-05 00:27
Should we hide/remove v3.0.0b2.post1 from pypi as it may break some protobuf users?

**Comment by jonparrott** [comment] 2016-03-05 01:49
@xfxyjwf I would prefer it if you did that or cut a new release to fix, as it will take some time for me to update all of our samples to point to gcloud-python==0.11.0 and currently mostly lower versions will be broken.

**Comment by silviulica** [comment] 2016-03-05 16:03
Feng/Josh I am ready to hide the 3.0.0b2.post1 release. We certainly need to understand better what is happening before unhiding. Just want one more team member to be aware of this before I actually do it. So I will wait today for a green light. In the meantime I am investigating root causes.

**Comment by haberman** [comment] 2016-03-05 21:29
Yes @silviulica please feel free to go ahead on hiding the broken release.

**Comment by silviulica** [comment] 2016-03-06 16:24
done
