### ISSUE TITLE
Protobuf-mode broken in emacs at head due to change in cc-mode internals

### ISSUE THREAD

**Issue by leadpipe** [google/protobuf#1083] opened 2015-12-31 17:42 UTC
Emacs 25, built from git head a couple of months ago, breaks protobuf-mode.  Here's the workaround from my .emacs file:

;; Note: this is required in emacs 25 as of Xmas 2015, to make
;; protobuf-mode work.  Just quotes nil.
(require 'protobuf-mode)
(c-lang-defconst c-cpp-matchers
  protobuf 'nil)

The breakage is due to a change from "eval" to "funcall" deep in the guts of cc-mode (in c-get-lang-constant, in cc-defs.el).  Protobuf-mode's way of killing C preprocessor syntax by defining c-cpp-matchers to nil no longer works.

**Comment by xfxyjwf** [comment] 2016-01-05 19:05
Hi @leadpipe, could you help send us a pull request to fix this? We don't know emacs well enough to fix this.

**Comment by ahyatt** [comment] 2016-01-29 03:10
Although I've seen this issue myself, I can't reproduce this issue with emacs -Q.  The problem may lie elsewhere.

**Comment by ahyatt** [comment] 2016-01-29 04:16
Actually, after a bit more playing around, I take it back.  This really is a problem with protobuf-mode.  If you compile protobuf-mode with emacs 24, it doesn't work with emacs 25.  I don't know why yet.

**Comment by anandolee** [comment] 2017-03-08 22:44
Looks like if you compile with emacs 25, it is not an issue? I guess it is a reasonable work round.
As Feng mentioned, we don't know emacs well enough to fix this.  I am closing it for clean up, feel free to reopen if needed.

**Closed by anandolee** 2017-03-08 22:44 UTC
Labels: help wanted
