### ISSUE TITLE
[v3.0.0-beta] Python 3 can't import properly related proto files

### ISSUE THREAD

**Issue by omikronsc** [google/protobuf#762] opened 2015-08-27 10:45 UTC
Hello!

I have two proto files core.proto and items.proto, items.proto import core.proto. They are generated into project's subdirectory src_gen. Problem is that in generated Python code there is import in items_pb2.py:

``` python
    import core_pb2 as core__pb2
```

It doesn't work in Python 3 since it's relative import and syntax for relative import changed in Python 3. It should be (at the begining for python 2.5+ compatibility):

``` python
from __future__ import absolute_import 
```

And replace import:

```
    from . import core_pb2 as core__pb2
```

This is how I feel it should solved but I might be unaware of some other method. Is there any other solution?

**Comment by xdmiodz** [comment] 2015-11-19 21:28
Looks similar to #881, I think have a workaround/possible solution for the issue there

**Comment by omikronsc** [comment] 2015-11-20 08:42
Actually I used another trick to solve this issue. I run 2to3 on src_gen folder after every invoke to protoc and everything works properly both on Python 2.7 and 3

But it is what it is - a workaround.

**Comment by haberman** [comment] 2017-03-13 22:49
I think this is a duplicate of https://github.com/google/protobuf/issues/1491

**Closed by haberman** 2017-03-13 22:49 UTC
Labels: packaging & distribution, python
