### ISSUE TITLE
ValueError exception during serialization

### ISSUE THREAD

**Issue by Kentzo** [google/protobuf#1123] opened 2016-01-09 07:32 UTC
I have an odd exception in the following [method](https://github.com/google/protobuf/blob/v2.6.1/python/google/protobuf/internal/encoder.py#L367-L378):

```
  local_chr = _PY2 and chr or (lambda x: bytes((x,)))  ##PY25
##!PY25  local_chr = chr if bytes is str else lambda x: bytes((x,))
  def EncodeSignedVarint(write, value):
    if value < 0:
      value += (1 << 64)
    bits = value & 0x7f
    value >>= 7
    while value:
      write(local_chr(0x80|bits))
      bits = value & 0x7f
      value >>= 7
    return write(local_chr(bits))
```

It fails at `write(local_chr(0x80|bits))` with the `ValueError: bytes must be in range(0, 256)` message.

I cannot reproduce it locally, just have this traceback. The issue happens extremely rarely.
I'm using Python 3.5.0

**Comment by anandolee** [comment] 2017-04-11 23:34
Closing it for not able to reproduce.
#722 has changed this method to use six and hope it has been fixed by the change.

**Closed by anandolee** 2017-04-11 23:34 UTC
Labels: python
