### ISSUE TITLE
error: class ‘google::protobuf::internal::InternalMetadataWithArenaLite’ does not have any field named ‘InternalMetadataWithArenaBase’

### ISSUE THREAD

**Issue by httaotao** [google/protobuf#3066] opened 2017-05-07 04:11 UTC
when I install protobuf-master which  down from https://github.com/google/protobuf 
then during make ,it showed:

[root@master protobuf-master]# make 
make  all-recursive
make[1]: Entering directory `/usr/local/src/protobuf-master'
Making all in .
make[2]: Entering directory `/usr/local/src/protobuf-master'
make[2]: Leaving directory `/usr/local/src/protobuf-master'
Making all in src
make[2]: Entering directory `/usr/local/src/protobuf-master/src'
depbase=`echo google/protobuf/any.pb.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/sh ../libtool --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..    -pthread -DHAVE_PTHREAD=1  -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/any.pb.lo -MD -MP -MF $depbase.Tpo -c -o google/protobuf/any.pb.lo google/protobuf/any.pb.cc &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -Wall -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/any.pb.lo -MD -MP -MF google/protobuf/.deps/any.pb.Tpo -c google/protobuf/any.pb.cc  -fPIC -DPIC -o google/protobuf/.libs/any.pb.o
In file included from ./google/protobuf/metadata.h:41,
                 from ./google/protobuf/any.pb.h:27,
                 from google/protobuf/any.pb.cc:5:
./google/protobuf/metadata_lite.h: In constructor ‘google::protobuf::internal::InternalMetadataWithArenaLite::InternalMetadataWithArenaLite(google::protobuf::Arena*)’:
./google/protobuf/metadata_lite.h:170: error: class ‘google::protobuf::internal::InternalMetadataWithArenaLite’ does not have any field named ‘InternalMetadataWithArenaBase’
In file included from ./google/protobuf/any.pb.h:27,
                 from google/protobuf/any.pb.cc:5:
./google/protobuf/metadata.h: At global scope:
./google/protobuf/metadata.h:56: error: ‘google::protobuf::Arena* google::protobuf::internal::InternalMetadataWithArenaBase<T, Derived>::arena() const [with T = google::protobuf::UnknownFieldSet, Derived = google::protobuf::internal::InternalMetadataWithArena]’ cannot appear in a constant-expression
./google/protobuf/metadata.h:56: error: ISO C++ forbids declaration of ‘type name’ with no type
./google/protobuf/metadata.h:56: error: expected ‘;’ before ‘{’ token
./google/protobuf/metadata.h:58: error: expected ‘;’ before ‘void’
./google/protobuf/metadata.h: In constructor ‘google::protobuf::internal::InternalMetadataWithArena::InternalMetadataWithArena(google::protobuf::Arena*)’:
./google/protobuf/metadata.h:54: error: class ‘google::protobuf::internal::InternalMetadataWithArena’ does not have any field named ‘InternalMetadataWithArenaBase’
make[2]: *** [google/protobuf/any.pb.lo] Error 1
make[2]: Leaving directory `/usr/local/src/protobuf-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/src/protobuf-master'
make: *** [all] Error 2
[root@master protobuf-master]# 

my os is centos 6.8 x86_64

**Comment by xfxyjwf** [comment] 2017-05-08 18:38
I believe the issue is fixed in https://github.com/google/protobuf/pull/3062

**Closed by xfxyjwf** 2017-05-08 18:38 UTC
