### ISSUE TITLE
Error Message in Executing GRPC 

### ISSUE THREAD

**Issue by Kartikkh** [google/protobuf#4656] opened 2018-05-21 13:11 UTC
proto/xyz_fill.pb.go:1028:46: undefined: proto.InternalMessageInfo

This message is coming when I am executing Go build, Initially, it was working fine! 
Is this the version update ?
How to fix this ?

**Comment by acozzette** [comment] 2018-05-21 20:39
I think this is a duplicate of #4582 and that issue has links explaining how to resolve this problem.

**Closed by acozzette** 2018-05-21 20:39 UTC
Labels: go
