### ISSUE TITLE
Building protoc using MSVS projects doesn't work: Ruby-related link error.

### ISSUE THREAD

**Issue by vadz** [google/protobuf#184] opened 2015-01-30 01:27 UTC
With the current (8ccaa42ffbe020f3d74ec90e954dd45a27ec32c6) sources, protoc doesn't link as the project doesn't include `ruby_generator.cc` but `google::protobuf::compiler::ruby::Generator` is unconditionally referenced in `main.cc`. Unfortunately fixing this is not as easy as just adding this file to the project as it doesn't compile with MSVS (tons of errors, didn't have time to really look at them and it was simpler to just disable Ruby generation for me).

**Comment by cfallin** [comment] 2015-01-30 02:11
Hi @vadz, I don't have access to Visual Studio at the moment, but could you copy/paste the errors you're seeing so that I have some idea of what we're looking at? Thanks!

**Comment by vadz** [comment] 2015-01-30 11:32
Here they are:

	1>ClCompile:
	1>  ruby_generator.cc
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(50): error C2065: 'uint32_t' : undeclared identifier
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(50): error C2146: syntax error : missing ')' before identifier 'value'
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(50): error C2059: syntax error : ')'
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(67): error C2065: 'uint32_t' : undeclared identifier
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(67): error C2146: syntax error : missing ')' before identifier 'value'
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(67): error C2374: 'google::protobuf::compiler::ruby::IntToString' : redefinition; multiple initialization
	1>          ...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(50) : see declaration of 'google::protobuf::compiler::ruby::IntToString'
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(67): error C2059: syntax error : ')'
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(67): error C2143: syntax error : missing ';' before '{'
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(67): error C2447: '{' : missing function header (old-style formal list?)
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(119): error C3861: 'IntToString': identifier not found
	1>...\protobuf\src\google\protobuf\compiler\ruby\ruby_generator.cc(156): error C3861: 'IntToString': identifier not found

**Comment by cfallin** [comment] 2015-01-30 18:13
This is an issue caused by using `uint32_t` instead of `uint32`. Sorry about that.

The PR #183 is addressing this issue.

**Comment by ennerf** [comment] 2015-02-01 00:37
Unfortunately I saw your PR too late. PR #186 addresses the type issue as well as the vc project file includes.

**Comment by haberman** [comment] 2015-07-07 01:28
Looks like this was fixed a while ago. I'll close this for now -- please re-open if it is still an issue.

**Closed by haberman** 2015-07-07 01:28 UTC
