### ISSUE TITLE
Python protobuf dynamic decoding

### ISSUE THREAD

**Issue by nicola-lunghi** [google/protobuf#4775] opened 2018-06-18 09:44 UTC
Dear protobuf developer, 
I have a bunch of different .proto file and I have a data stream coming through MQTT messages.

I need to develop a program (using python) that:

1) get the binary data from the MQTT
2) try to identify the "kind" of protobuf message from the .proto file in a folder
3) decode the message and print the data

I have some questions:

1) is possible from the binary data itself to identify the "protobuf type" of a message?
2) is possible with the python  api to read a .proto file at runtime and generate the parsing classes without compiling the proto first? performance is not an issue but the functionality to change the .proto file without relaunching protoc is 

Do you have an example of that?

I've found in the code the reflection api and for example the descriptor pool database that seems to be what I'm searching for 

I've also found this
https://vdna.be/blog/index.php/2016/05/google-protobuf-at-run-time-deserialization-example-in-c/

What I miss is an update example about how to use those API
the documentation about it is pretty laconic

https://developers.google.com/protocol-buffers/docs/pythontutorial#advanced-usage

Thanks
Nick

**Comment by acozzette** [comment] 2018-06-18 21:01
To answer your first question, a serialized protocol buffer does not identify its type, so when you parse a message you have to know what kind of type you're expecting. If you want to be able to parse multiple message types, one easy way to accomplish that is to put all the message types inside a `oneof` field in a wrapper message.

For your second question, unfortunately as far as I know there is no good way to have changes to a .proto file take effect automatically without you rebuilding the protos with protoc. In C++ and Java there is a DynamicMessage which allows you to manipulate messages of a type that's only known at runtime, but I don't think this exists in Python. And even with that approach, you end up with messages that you can only access via the reflection API (no generated accessors, etc.), so that doesn't sound like what you are looking for.

**Comment by nicola-lunghi** [comment] 2018-06-19 08:41
Hi @acozzette 
thanks for your response.

I need to explain my problem better.
I have a bunch of .proto files coming from different part of the system.
I need to develop a "viewer" that give the possibility to select a proto file and decode messages for debugging purpose.

eg a developer need to see a particular stream of data and type

proto_decoder -t stream1/data1 -p myprotocol.proto

and see all message in a readable format

  name: "demo.proto"
  package: "demo"
  message {
      name: "n"
      number: 2
      label: "pippo"
      type: TEST_OBJ
    }

in the same manner as the protoc application --decode option.
I cannot use the protoc directly because I have to get the stream of data from a server.

The first part (not needed but cool too have was about the possibility of having in a folder a list of .proto files 
and have the software to try to decode the messages trying those one by one (until it doesn't get an error)

Under Python this seemed more simpe because the protobuf there is generated at runtime!
Here is a generated demo_pb2.py as you see the classes are constructed at runtime with

_reflection.GeneratedProtocolMessageType(

```
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='demo',
  syntax='proto3',
  serialized_pb=_b('\n\ndemo.proto\x12\x04\x64\x65mo\"\x11\n\x04\x64\x65mo\x12\t\n\x01n\x18\x01 \x03(\x05\x62\x06proto3')
)




_DEMO = _descriptor.Descriptor(
  name='demo',
  full_name='demo.demo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='demo.demo.n', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=37,
)

DESCRIPTOR.message_types_by_name['demo'] = _DEMO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

demo = _reflection.GeneratedProtocolMessageType('demo', (_message.Message,), dict(
  DESCRIPTOR = _DEMO,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.demo)
  ))
_sym_db.RegisterMessage(demo)

```

An interesting class is the descriptor pool class but I don't understand how to populate the FileDescriptor class with a list of file names and the differences between FileDescriptorProto and FileDescriptor...

**Comment by acozzette** [comment] 2018-06-20 17:38
Ok, I think what you are trying to do should be doable. `reflection.ParseMessage` provides the basic functionality of parsing a message based on a given descriptor: https://github.com/google/protobuf/blob/d36c0c538a545fac5d9db6ba65c525246d4efa95/python/google/protobuf/reflection.py#L67

I think the best way to get the descriptors you need is to call `protoc` with `--descriptor_set_out=...` to have it generate them for you. I am not too familiar with the Python implementation but I believe `FileDescriptor` is just a nicer in-memory representation of the raw `FileDescriptorProto` message.

**Comment by nicola-lunghi** [comment] 2018-06-22 11:47
Hi @acozzette
thank again for your response I think it's in the right direction.

I've tried to use that function but it require a descriptor class

So to make it work I need a way to generate a Descriptor class from the
descriptor binary representation.

here's what I tried (it doesn't work...)

```
from google.protobuf import reflection as _reflection
from google.protobuf.descriptor_pb2 import FileDescriptorSet

_DESCR_FILE = 'automation.descr'
_BIN_FILE = 'automation.bin'

with open(_DESCR_FILE, 'rb') as f:
    descriptorFile = f.read()

descriptorSetObject = FileDescriptorSet.parseFrom(descriptorFile)

with open(_BIN_FILE, 'rb') as f:
    bin_file = f.read()

_decoded_msg = _reflection.ParseMessage(descriptorSetObject, bin_file)

``` 
Anyone else can help?

Thanks
Nick

**Comment by acozzette** [comment] 2018-06-22 16:17
I think the problem is that `reflection.ParseMessage` takes a message descriptor but you're passing it a `FileDescriptorSet`. You have to find the `DescriptorProto` for the message you're interested in within the `FileDescriptorSet`, and then call `descriptor.MakeDescriptor(...)` to convert that into a descriptor object which you can then pass to `reflection.ParseMessage`. There's some example code in reflection_test.py here: https://github.com/google/protobuf/blob/6a4fec616ec4b20f54d5fb530808b855cb664390/python/google/protobuf/internal/reflection_test.py#L1155

**Comment by acozzette** [comment] 2018-06-29 23:41
Let me close this just to tidy up my open issues, but feel free to reply here again if you have more questions.

**Closed by acozzette** 2018-06-29 23:41 UTC
Labels: python, question
