### ISSUE TITLE
MacOS Sierra 10.12.1 make issue 

### ISSUE THREAD

**Issue by nabarunnag** [google/protobuf#2347] opened 2016-11-09 19:09 UTC
While build the project in a MacOS dev environment 10.12  I have some errors about the project using deprecated function calls.
```
In file included from /Users/nnag/Development/quickstep/test2/quickstep/third_party/protobuf/src/google/protobuf/stubs/atomicops_internals_x86_msvc.cc:37:
In file included from /Users/nnag/Development/quickstep/test2/quickstep/third_party/protobuf_cmake/../protobuf/src/google/protobuf/stubs/atomicops.h:199:
/Users/nnag/Development/quickstep/test2/quickstep/third_party/protobuf_cmake/../protobuf/src/google/protobuf/stubs/atomicops_internals_macosx.h:138:9: error: In file included from /Users/nnag/Development/quickstep/test2/quickstep/third_party/protobuf/src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc'OSAtomicCompareAndSwap64': 36is:
 In file included from deprecated:/Users/nnag/Development/quickstep/test2/quickstep/third_party/protobuf_cmake/../protobuf/src/google/protobuf/stubs/atomicops.h :first199 :
deprecated /Users/nnag/Development/quickstep/test2/quickstep/third_party/protobuf_cmake/../protobuf/src/google/protobuf/stubs/atomicops_internals_macosx.hin: 138macOS: 910.12:  - errorUse:
      std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed) 'OSAtomicCompareAndSwap64'from  is<atomic>  deprecated:instead  first deprecated in macOS 10.12 -[-Werror,-Wdeprecated-declarations] Use
```

**Comment by acozzette** [comment] 2016-11-09 19:57
This looks like a duplicate of #2182; let me close this issue since there is already some discussion happening on the other one.

**Closed by acozzette** 2016-11-09 19:57 UTC
Labels: c++, cleanup

**Comment by nabarunnag** [comment] 2016-11-09 20:31
@acozzette Thank you !! i missed that thread
