### ISSUE TITLE
Ruby: significant memory leak

### ISSUE THREAD

**Issue by skippy** [google/protobuf#474] opened 2015-06-08 00:23 UTC
```ruby
require 'google/protobuf'
pool = Google::Protobuf::DescriptorPool.new
pool.build do
  add_message "M" do
    optional :foo, :string, 1
  end
end
M = pool.lookup("M").msgclass

# creates a ~50KB msg
m = M.new(:foo => ("hello" * 10_000));
data = M.encode(m);
5_000.times do
  mnew = M.decode(data); 
end;
```

and watch the memory explode.  I think this exists in very small msgs (like a few bytes) but it takes a lot longer to accumulate.  This occurs with the C-ext but not under jruby.

@cfallin let me know what you think.  I'll see if I can spend a few hrs later this week to see if I can track it down.  I'm sure it has to do with ~~UDP~~ upb and releasing memory when ruby is finished with the object.

**Comment by cfallin** [comment] 2015-06-08 00:41
@skippy Thanks for finding this. As just noted elsewhere too -- I've handed off Ruby  to @haberman. Josh, could you take a look? Thanks!

**Comment by skippy** [comment] 2015-06-08 02:04
ah!  poor josh :)  but thanks @cfallin for all your help with my PRs.  I appreciate it.

**Comment by haberman** [comment] 2015-06-08 02:46
Hi @skippy -- thanks for the report and sorry I haven't been super prompt on your other issues. I am juggling a lot of things so I hope you'll bear with me if I'm not quite as responsive as Chris was!

I wasn't able to reproduce a memory leak here. I tried your program on OS X with both the latest gem and the code from Git. I increased your iteration count to 5,000,000 and watched the process in Activity Monitor. The memory size of the process seemed pretty stable over the 30 seconds or so that the test took to run.

Let me know if you have any other way that can reproduce a leak here.

**Comment by skippy** [comment] 2015-06-08 17:10
hey @haberman ; gosh, no worries at all!  you folks are pretty damn responsive. (and if either of you find yourself in PDX, look me up; I believe I owe you folks a beer)

and a huge 'huh!'.  What version of ruby are you using?  I'm running on `ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]`.  I fire up `pry` and can immediately see RSS memory explode by ~ 250 megs per run (which corresponds to 50KB msg * 5_000 times).  I tried my current branch (#396), current master, and back to c881159557398c915b6b279b45c618732741416b, and I can recreate it on ruby 2.2.0p0. 

I was running my tests under `pry`.  I put a trailing `;` at the end of the line because if I don't, `pry` and `irb` will print the result out, which can get quite long for a 50KB text string.  However, I was tinkering and noticed that `irb` wasn't running the `5_000.times` loop if there was a `;` before it.  That is damn odd; I'm not sure what is going on there.  But if you remove all the `;` and then copy/paste that into `irb`, I then see the memory explode.  

I'm still learning how to use `GC.stat`, and I know it is different between ruby versions, but if you run the following code, which also forces a GC, you can see the memory usage explode.

```ruby
require 'google/protobuf'
pool = Google::Protobuf::DescriptorPool.new
pool.build do
  add_message "M" do
    optional :foo, :string, 1
  end
end
M = pool.lookup("M").msgclass

# creates a ~50KB msg
m = M.new(:foo => ("hello" * 10_000))
data = M.encode(m)
GC.start
puts "------------ pre run"
GC.stat
5_000.times do
  M.decode(data)
end
GC.start
puts "------------ post run"
GC.stat
```

let me know if that helps?  If you can't recreate it, I'll be a bit stumped, but I can try a few other things in my environment

**Comment by haberman** [comment] 2015-06-12 20:31
Wow, when I tried Ruby 2.2 I was indeed able to reproduce this. In Ruby 2.1 everything works as expected. But in Ruby 2.2, the heap grows without bound. I ran this under massif, and here is the heap profile:

```
99.95% (4,696,677,872B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->99.88% (4,693,487,455B) 0x4ED42B2: ruby_xmalloc2 (gc.c:7361)
| ->99.84% (4,691,610,785B) 0x4FA2D27: str_buf_cat (string.c:2205)
| | ->99.84% (4,691,608,200B) 0x7CDEF9D: stringdata_handler (encode_decode.c:167)
| | | ->99.84% (4,691,608,200B) 0x7CF6FC5: upb_pbdecoder_decode (upb.h:6310)
| | |   ->99.84% (4,691,608,200B) 0x7CE0F3A: Message_decode (upb.h:6243)
| | |     ->99.84% (4,691,608,200B) 0x4FFFB7C: vm_call_cfunc (vm_insnhelper.c:1382)
| | |       ->99.84% (4,691,513,991B) 0x5007620: vm_exec_core (insns.def:1054)
| | |       | ->99.84% (4,691,513,991B) 0x500ACD2: vm_exec (vm.c:1400)
| | |       |   ->99.84% (4,691,513,991B) 0x5012EB7: rb_yield (vm.c:813)
| | |       |     ->99.84% (4,691,513,991B) 0x4F0AACC: int_dotimes (numeric.c:3864)
| | |       |       ->99.84% (4,691,513,991B) 0x4FFFB7C: vm_call_cfunc (vm_insnhelper.c:1382)
| | |       |         ->99.84% (4,691,513,991B) 0x501678C: vm_call_method (vm_insnhelper.c:1691)
| | |       |           ->99.84% (4,691,513,991B) 0x50062ED: vm_exec_core (insns.def:1024)
| | |       |             ->99.84% (4,691,513,991B) 0x500ACD2: vm_exec (vm.c:1400)
| | |       |               ->99.84% (4,691,513,991B) 0x500C651: rb_iseq_eval_main (vm.c:1670)
| | |       |                 ->99.84% (4,691,513,991B) 0x4EB13D2: ruby_exec_internal (eval.c:252)
| | |       |                   ->99.84% (4,691,513,991B) 0x4EB374B: ruby_exec_node (eval.c:317)
| | |       |                     ->99.84% (4,691,513,991B) 0x4EB60AA: ruby_run_node (eval.c:309)
| | |       |                       ->99.84% (4,691,513,991B) 0x400879: main (main.c:36)
| | |       |-------------------------
| | |       ->00.00% (94,209B) in 1+ places, all below ms_print's threshold (01.00%)
| | |-------
| | ->00.00% (2,585B) in 1+ places, all below ms_print's threshold (01.00%)
| |-
| ->00.04% (1,876,670B) in 1+ places, all below ms_print's threshold (01.00%)
|-
->00.07% (3,190,417B) in 1+ places, all below ms_print's threshold (01.00%)
```

So it appears that string data we're appending into a Ruby string with `str_buf_cat` is indeed leaking. Since this works fine in Ruby 2.1 I can't help but wonder if this is a bug in Ruby. But I'll have to dig deeper before I can say for sure.

**Comment by skippy** [comment] 2015-06-14 05:07
oh interesting!  Good find.  A few things I dug up:

* the issue crops up between tags `v2_2_0_preview1` and `v2_2_0_preview2`.  There are many changes that went in between those versions (`git diff v2_2_0_preview1 v2_2_0_preview2 string.c` and `git log v2_2_0_preview1..v2_2_0_preview2 string.c`
* it is gone in 2.3.0-dev!
* I'm not exactly sure what the changes were that caused the problem; still looking, though I suspect this was the patch that fixed it 'https://github.com/ruby/ruby/commit/2b0a6f47ac9ea1ac81c9d438ac9bc8d38b46cb04`

I'm tempted to push a PR that just has a note in the README.md about `2.2`, but I am curious if how `encode_decode.c` is using this ruby method exacerbates the issues.  Thoughts?

**Comment by haberman** [comment] 2015-06-16 03:59
Thanks for bisecting this! Looks like it might be a bug in a limited number of Ruby versions.

It seems like the best thing to do is, for the broken Ruby versions, replace the use of `rb_str_cat(rb_str, str, len)` with the less-efficient sequence `rb_str_append(rb_str, rb_str_new(str, len))`.

**Comment by skippy** [comment] 2015-06-16 19:44
hmm... I tried that and I'm still getting a memory leak.  I'm also getting a bunch of segmentation faults, but I can't quite nail it down (ie, I can cause it to crash every time on production after 5-20 iterations, but I'm haven't yet been able to recreate it in a test case).  I'm not sure it is related but it is in the same area, though this time on the encoding rather than decoding side of things.

**Comment by skippy** [comment] 2015-06-17 00:35
segfaults (#502) seem to be unrelated.  I went back to earlier commits to see if this error lined up with that ticket, and it didn't.

**Comment by haberman** [comment] 2015-06-17 00:45
So if I'm understanding correctly, you're still getting a memory leak when you replace `rb_str_cat(rb_str, str, len)` with `rb_str_append(rb_str, rb_str_new(str, len))`? That is very strange.

**Comment by skippy** [comment] 2015-06-22 23:49
yep

**Comment by haberman** [comment] 2015-06-23 02:39
This is very strange.

I was able to reproduce your results: the leak occurs even when using `rb_str_append(rb_str, rb_str_new(str, len))`. This it sort of understandable, since internally it appears to delegate to `rb_str_cat()` anyways.

However I can't seem to reproduce this leak with a pure Ruby script, as I would expect to be able to if `rb_str_append()` is truly this broken.

In any case, I seem to be able to fix the leak if I use this very manual code:

```ruby
static size_t stringdata_handler(void* closure, const void* hd,
                                 const char* str, size_t len,
                                 const upb_bufhandle* handle) {
  VALUE rb_str = (VALUE)closure;
  size_t oldlen = RSTRING_LEN(rb_str);
  rb_str_modify_expand(rb_str, len);
  char *p = RSTRING_PTR(rb_str);
  memcpy(p + oldlen, str, len);
  rb_str_set_len(rb_str, oldlen + len);
  return len;
}
```

Maybe that is our best option right now. Thoughts?

**Comment by skippy** [comment] 2015-07-03 20:03
@haberman pardon the delay in getting back to you!

nod; I would say lets put that patch in.  I'm also going to open a bug report in ruby (https://bugs.ruby-lang.org/) and link to this ticket to get some feedback.  My main concern is that while it looks like it was 'fixed' in 2.3, that it was really a byproduct of another issue and fix, and that this could crop up again.  

but in the meanwhile, adding this in seems like a good thing.  thanks for the fix!

**Comment by skippy** [comment] 2015-07-03 20:12
opened here: https://bugs.ruby-lang.org/issues/11328

I'll be curious to see what comes from that.

**Comment by nagachika** [comment] 2015-07-06 13:25
Hi,
As I commented at ticket https://bugs.ruby-lang.org/issues/11328#note-2
I'd like to know exact `ruby -v` which reproduce the issue and I'd like to create small, self-contained code to reproduce.

**Comment by haberman** [comment] 2015-07-09 00:29
Fixed by the attached PR.

**Closed by haberman** 2015-07-09 00:29 UTC
