### ISSUE TITLE
Python - string representation of objects should be `unicode`s, not `str`s

### ISSUE THREAD

**Issue by jerjou** [google/protobuf#2277] opened 2016-10-21 21:48 UTC
I have a script that makes [grpc](http://grpc.io) calls, that return text that's potentially in a different language. In the code, I print out the list of objects who have the attribute transcript, that is the unicode with the text. However, if the text is in fact a double-byte character, it's printed out as escape sequences. Printing out the transcript attribute directly correctly prints out the desired character.

I suspect this is because the **str** of the protoc-generated response objects are str objects instead of unicode objects. Given that in python3, all string objects default to unicode objects, it might be prudent for the string representations of grpc-generated objects also be unicode objects.

**Comment by xfxyjwf** [comment] 2016-10-22 04:30
I'm pretty sure that's working as intended: by default we print all non-ascii characters in escaped sequence. To print non-ascii character without escaping, you can use the text_format utility:
```python
from google.protobuf import text_format
# The default behavior.
print text_format.MessageToString(msg)
# The behavior you want.
print text_format.MessageToString(msg, as_utf8 = True)
```

**Comment by jerjou** [comment] 2016-10-24 18:32
Wouldn't it be better if it was unicode, though? Wouldn't that be more consistent with python3, which defaults to unicode? As well as being more friendly to non-english users?u

**Comment by anandolee** [comment] 2017-03-08 19:45
It's not nice to change the default behavior which breaks many existing projects. I think Feng's suggestion is good enough for your case.

Closing it for clean up. Feel free to reopen if it is still an issue for you

**Closed by anandolee** 2017-03-08 19:45 UTC
Labels: python
