### ISSUE TITLE
xcode 8.3 error

### ISSUE THREAD

**Issue by DylanDu123** [google/protobuf#2916] opened 2017-03-29 02:58 UTC
array parameter ismissing a nullabillty type specifler (_Nonnul,_Nullable,or _null_unspecifled)

**Comment by saldous** [comment] 2017-03-29 03:43
Same, I'm seeing 238 of these issues with Protobuf since upgrading to Xcode 8.3.

**Comment by awuu** [comment] 2017-03-29 09:21
#2626

**Comment by awuu** [comment] 2017-03-29 10:00
Non-portable path to file '<protobuf/Any.pbobjc.h>'; specified path differs in case from file name on disk

**Comment by mikestalker** [comment] 2017-03-29 12:56
Yep. Same situation.

**Comment by terflogag** [comment] 2017-03-29 13:03
Same situation 👍

**Comment by alexdd55** [comment] 2017-03-29 13:47
same here 👍

**Comment by thomasvl** [comment] 2017-03-29 14:26
This is a duplicate of #2625.  It's already fixed on `master` and the fix has been pulled to the 3.2.x branch.  @TeBoring is cutting a 3.2.1 release soon so folks can use that to pull it.

**Closed by thomasvl** 2017-03-29 14:26 UTC

**Comment by saldous** [comment] 2017-03-29 17:16
Thanks, I didn't add Protobuf to my podfile, another google pod I use must be pulling it automatically, so I don't know how to force it to pull from master (either Firebase or AdMod must be pulling it)

**Comment by mikestalker** [comment] 2017-03-31 09:42
@thomasvl i have the same situation as @saldous . So how we can get rid of this warnings?

**Comment by iValkou** [comment] 2017-03-31 10:43
@thomasvl The same issue

**Comment by SebastianKumor** [comment] 2017-03-31 11:59
i had the same issue, the pod was pulled with firebase, add this to your podfile `pod 'Protobuf', :git => 'https://github.com/google/protobuf.git'` and run pod install, it solved my problem with the warnings.

**Comment by saldous** [comment] 2017-03-31 12:34
@SebastianKumor thanks! 👍
