### ISSUE TITLE
protobuff3.0.0 cannot use in unity3d 5.3.2 ,why?

### ISSUE THREAD

**Issue by zhenyao2008** [google/protobuf#1237] opened 2016-02-14 04:50 UTC
Unity5.3.2 can not load google.protobuff.dll ,i do not konw why ?

here is [error：](https://mail.qq.com/cgi-bin/readmail?sid=EFiPMdgkbSmWATBm&mailid=ZL4314-4aksWbAbcjaJb14ILfqBf62&nocheckframe=true&t=attachpreviewer&select=1&selectfile=&seq=)

**Comment by zhenyao2008** [comment] 2016-02-14 04:51
C# 版本

**Comment by zhenyao2008** [comment] 2016-02-14 05:08
this is error:
Unhandled Exception: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.

  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)

  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 

  at Mono.CSharp.RootNamespace.ComputeNamespaces (System.Reflection.Assembly assembly, System.Type extensionType) [0x00000] in <filename unknown>:0 

  at Mono.CSharp.RootNamespace.ComputeNamespace (Mono.CSharp.CompilerContext ctx, System.Type extensionType) [0x00000] in <filename unknown>:0 

  at Mono.CSharp.GlobalRootNamespace.ComputeNamespaces (Mono.CSharp.CompilerContext ctx) [0x00000] in <filename unknown>:0 

  at Mono.CSharp.Driver.LoadReferences () [0x00000] in <filename unknown>:0 

  at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0 

  at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0 

The following assembly referenced from E:\Unity5Projects\test\Assets\test\Google.Protobuf.dll could not be loaded:
     Assembly:   System.Runtime    (assemblyref_index=0)
     Version:    4.0.0.0
     Public Key: b03f5f7f11d50a3a
The assembly was not found in the Global Assembly Cache, a path listed in the MONO_PATH environment variable, or in the location of the executing assembly (E:\Unity5Projects\test\Assets\test\).

Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Missing method .ctor in assembly E:\Unity5Projects\test\Assets\test\Google.Protobuf.dll, type System.Runtime.Versioning.TargetFrameworkAttribute
Can't find custom attr constructor image: E:\Unity5Projects\test\Assets\test\Google.Protobuf.dll mtoken: 0x0a000010

**Comment by zhenyao2008** [comment] 2016-02-14 06:44
why protobuff 3.0.0 must at .net 4.5 complic ?

unity3d  can support higtest  .net that is  3.5 ?

what can i do now?  i must use unity3d and must use protobuff ?

Looking forward to you to solve this problem~~~

**Comment by Extrawurst** [comment] 2016-02-14 09:36
for the time being if you are not locked in on proto 3 features: https://github.com/mgravell/protobuf-net

**Comment by zhenyao2008** [comment] 2016-02-14 09:42
i am sorry,i do not understand your mean .

what can i do now ?

**Comment by Extrawurst** [comment] 2016-02-14 10:13
what i mean is: as long as this official protobuf c# implementation does not support the .net version compatible with unity you can go with the protobuf-net implementation that i linked above.
also note that this is a dup of #644

**Comment by haberman** [comment] 2016-02-14 19:16
@jskeet any ideas?

**Comment by jskeet** [comment] 2016-02-14 20:30
Yes, basically what @Extrawurst said: we don't support Unity at the moment. This is indeed a duplicate of #644.

The old proto2 project at http://github.com/jskeet/protobuf-csharp-port works to *some* extent with Unity, but there have been issues with it in the past, usually due to bugs in the version of Mono that Unity uses.

We'd like to support Unity in the future, but don't have any concrete plans/timelines at the moment.
Closing this issue as it's easier to keep just one issue tracking Unity support.

**Closed by jskeet** 2016-02-14 20:30 UTC
Labels: c#
