### ISSUE TITLE
CMake: install.cmake messes up declarations in target_include_directories

### ISSUE THREAD

**Issue by robiwano** [google/protobuf#1543] opened 2016-05-17 05:38 UTC
I've encountered a problem with TARGET_INCLUDE_DIRECTORIES not working as expected. Nominally if my target APP depens on libprotobuf, the PUBLIC part
of TARGET_INCLUDE_DIRECTORIES should propagate to target APP.

This does not work however, and the reason being is the install.cmake file in protobuf/cmake. The first section in install.cmake:

foreach(_library
  libprotobuf-lite
  libprotobuf
  libprotoc)
  set_property(TARGET ${_library}
    PROPERTY INTERFACE_INCLUDE_DIRECTORIES
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
  install(TARGETS ${_library} EXPORT protobuf-targets
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT ${_library}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT ${_library}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT ${_library})
endforeach()

messes up the TARGET_INCLUDE_DIRECTORIES declarations.

If I comment out include(install.cmake) (row 153 in CMakeLists.txt), everything works as expected and the include directory declarations are propagated correctly to the dependant targets.

At this point, the only workaround is to omit the "include(install.cmake)" statement.

**Comment by xfxyjwf** [comment] 2017-03-08 23:08
I'm not familiar with cmake enough to tell whether the observed behavior is a bug or working as intended. Hopefully @yeswalrus @podsvirov who originally contributed install.cmake will know the answer here...

**Comment by yeswalrus** [comment] 2017-05-30 20:30
looks like this has been fixed by the addition of the $<BUILD_INTERFACE> Generator expression

**Closed** 2017-12-11 21:07 UTC
Labels: bug, c++, cmake, help wanted, packaging & distribution, to close
