### ISSUE TITLE
NameError: name 'long' is not defined in python\google\protobuf\internal\reflection_test.py:639

### ISSUE THREAD

**Issue by techkey** [google/protobuf#1504] opened 2016-05-08 13:45 UTC
Hi, Python 3.x has no `long` type.

`python\google\protobuf\internal\reflection_test.py`

``` python
632    try:
633      integer_64 = long
634    except NameError: # Python3
635      integer_64 = int
636    if struct.calcsize('L') == 4:
637      # Python only has signed ints, so 32-bit python can't fit an uint32
638      # in an int.
639      TestGetAndDeserialize('optional_uint32', 1 << 31, long)
640    else:
641      # 64-bit python can fit uint32 inside an int
642      TestGetAndDeserialize('optional_uint32', 1 << 31, int)
643    TestGetAndDeserialize('optional_int64', 1 << 30, integer_64)
644    TestGetAndDeserialize('optional_int64', 1 << 60, integer_64)
645    TestGetAndDeserialize('optional_uint64', 1 << 30, integer_64)
646    TestGetAndDeserialize('optional_uint64', 1 << 60, integer_64)
```

After changing `long` to `integer_64` on line 639 all tests return `ok`. 

My question is: should `long` be `integer_64`?

Cornelis

**Comment by CDLuminate** [comment] 2016-11-25 15:00
This issue seems to be solved in master?
https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/reflection_test.py#L658-L659

@xfxyjwf

**Comment by xfxyjwf** [comment] 2016-11-28 18:50
Yes, the issue is fixed in master now.

**Closed by xfxyjwf** 2016-11-28 18:50 UTC
Labels: bug, python
