### ISSUE TITLE
unresolved external symbol when compile protoc with vs2015CTP in release mode (protobuf-3.0.0-alpha-2)

### ISSUE THREAD

**Issue by toddwong** [google/protobuf#240] opened 2015-03-13 08:16 UTC
The following error reported:
```
libprotobuf.lib(generated_message_reflection.obj) : error LNK2019: unresolved external symbol "public: static class google::protobuf::Message * __cdecl google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message>::NewFromPrototype(class google::protobuf::Message const *,class google::protobuf::Arena *)" (?NewFromPrototype@?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@SAPAVMessage@34@PBV534@PAVArena@34@@Z) referenced in function "private: void __thiscall google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInnerLoop<class google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message> >(void * *,void * *,int,int)" (??$MergeFromInnerLoop@V?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@AAEXPAPAX0HH@Z)
```

And a suspicious warning:
```
..\src\google\protobuf\generated_message_reflection.cc(2152): warning C4506: no definition for inline function 'google::protobuf::Message *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::NewFromPrototype(const GenericType *,google::protobuf::Arena *)'
          with
          [
              GenericType=google::protobuf::Message
          ]
```

The full output:
```
1>------ Build started: Project: libprotobuf, Configuration: Release Win32 ------
1>  arena.cc
1>  arenastring.cc
1>  importer.cc
1>  parser.cc
1>  descriptor.cc
1>  descriptor.pb.cc
1>  descriptor_database.cc
1>  dynamic_message.cc
1>  extension_set.cc
1>  extension_set_heavy.cc
1>  generated_message_reflection.cc
1>..\src\google\protobuf\generated_message_reflection.cc(2152): warning C4506: no definition for inline function 'google::protobuf::Message *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::NewFromPrototype(const GenericType *,google::protobuf::Arena *)'
1>          with
1>          [
1>              GenericType=google::protobuf::Message
1>          ]
1>  generated_message_util.cc
1>  coded_stream.cc
1>  gzip_stream.cc
1>  printer.cc
1>  strtod.cc
1>  tokenizer.cc
1>  zero_copy_stream.cc
1>  zero_copy_stream_impl.cc
1>  zero_copy_stream_impl_lite.cc
1>  Generating Code...
1>  Compiling...
1>  map_field.cc
1>  message.cc
1>  message_lite.cc
1>  reflection_ops.cc
1>  repeated_field.cc
1>  service.cc
1>  atomicops_internals_x86_gcc.cc
1>  atomicops_internals_x86_msvc.cc
1>  common.cc
1>  once.cc
1>  stringprintf.cc
1>  structurally_valid.cc
1>  strutil.cc
1>..\src\google\protobuf\stubs\strutil.cc(1229): warning C4456: declaration of 'snprintf_result' hides previous local declaration
1>  ..\src\google\protobuf\stubs\strutil.cc(1213): note: see declaration of 'snprintf_result'
1>..\src\google\protobuf\stubs\strutil.cc(1278): warning C4456: declaration of 'snprintf_result' hides previous local declaration
1>  ..\src\google\protobuf\stubs\strutil.cc(1268): note: see declaration of 'snprintf_result'
1>  substitute.cc
1>  text_format.cc
1>  unknown_field_set.cc
1>  wire_format.cc
1>  wire_format_lite.cc
1>  Generating Code...
1>  libprotobuf.vcxproj -> D:\protobuf-3.0.0-alpha-2\vsprojects\Release\libprotobuf.lib
2>------ Build started: Project: libprotoc, Configuration: Release Win32 ------
2>  code_generator.cc
2>  command_line_interface.cc
2>  cpp_enum.cc
2>  cpp_enum_field.cc
2>  cpp_extension.cc
2>  cpp_field.cc
2>  cpp_file.cc
2>  cpp_generator.cc
2>  cpp_helpers.cc
2>  cpp_map_field.cc
2>  cpp_message.cc
2>  cpp_message_field.cc
2>  cpp_primitive_field.cc
2>  cpp_service.cc
2>  cpp_string_field.cc
2>  javanano_enum.cc
2>  javanano_enum_field.cc
2>  javanano_extension.cc
2>  javanano_field.cc
2>  javanano_file.cc
2>  Generating Code...
2>  Compiling...
2>  javanano_generator.cc
2>  javanano_helpers.cc
2>  javanano_map_field.cc
2>  javanano_message.cc
2>  javanano_message_field.cc
2>  javanano_primitive_field.cc
2>  java_context.cc
2>  java_doc_comment.cc
2>  java_enum.cc
2>  java_enum_field.cc
2>  java_extension.cc
2>  java_field.cc
2>  java_file.cc
2>  java_generator.cc
2>  java_generator_factory.cc
2>  java_helpers.cc
2>  java_lazy_message_field.cc
2>  java_map_field.cc
2>  java_message.cc
2>  java_message_field.cc
2>  Generating Code...
2>  Compiling...
2>  java_name_resolver.cc
2>  java_primitive_field.cc
2>  java_service.cc
2>  java_shared_code_generator.cc
2>  java_string_field.cc
2>  plugin.cc
2>  plugin.pb.cc
2>  python_generator.cc
2>..\src\google\protobuf\compiler\python\python_generator.cc(705): warning C4456: declaration of 'm' hides previous local declaration
2>  ..\src\google\protobuf\compiler\python\python_generator.cc(645): note: see declaration of 'm'
2>  ruby_generator.cc
2>  subprocess.cc
2>  zip_writer.cc
2>  Generating Code...
2>  libprotoc.vcxproj -> D:\protobuf-3.0.0-alpha-2\vsprojects\Release\libprotoc.lib
3>------ Build started: Project: protoc, Configuration: Release Win32 ------
3>  main.cc
3>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification
3>libprotobuf.lib(generated_message_reflection.obj) : error LNK2019: unresolved external symbol "public: static class google::protobuf::Message * __cdecl google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message>::NewFromPrototype(class google::protobuf::Message const *,class google::protobuf::Arena *)" (?NewFromPrototype@?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@SAPAVMessage@34@PBV534@PAVArena@34@@Z) referenced in function "private: void __thiscall google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInnerLoop<class google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message> >(void * *,void * *,int,int)" (??$MergeFromInnerLoop@V?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@AAEXPAPAX0HH@Z)
3>Release\protoc.exe : fatal error LNK1120: 1 unresolved externals
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Any suggestion or workaround will be appreciated.

**Comment by pherl** [comment] 2015-03-16 23:32
The warning looks suspicious indeed. Might be a VS2015 bug? Probably worth a bug report to the VS community as well.

**Comment by breathe67** [comment] 2015-05-08 16:03
I'm having this problem too, right after migrating my project to VC 2015 Community RC.

**Comment by Waty** [comment] 2015-05-11 15:21
Same problem here

**Comment by ml232528** [comment] 2015-06-25 06:27
+1

**Comment by toddwong** [comment] 2015-07-07 13:07
The problem has gone with visual studio 2015 rc. So this is indeed a bug of vs, not protobuf.

**Comment by breathe67** [comment] 2015-07-07 13:47
Did MS just release a new 2015 RC ?  The error showed up when I switched to
2015 RC (community) about two months ago.

**Comment by Waty** [comment] 2015-07-07 21:47
I can still reprocude this issue using Microsoft Visual Studio Enterprise 2015 RC.
The project compiles correctly in debug configuration, but release mode throws the following error:

    libprotobuf.lib(generated_message_reflection.obj) : error LNK2019: unresolved external symbol "public: static class google::protobuf::Message * __cdecl google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message>::NewFromPrototype(class google::protobuf::Message const *,class google::protobuf::Arena *)" (?NewFromPrototype@?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@SAPAVMessage@34@PBV534@PAVArena@34@@Z) referenced in function "private: void __thiscall google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInnerLoop<class google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message> >(void * *,void * *,int,int)" (??$MergeFromInnerLoop@V?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@AAEXPAPAX0HH@Z)

And this warning:

    1>  generated_message_reflection.cc
    1>..\src\google\protobuf\generated_message_reflection.cc(2157): warning C4506: no definition for inline function 'google::protobuf::Message *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::NewFromPrototype(const GenericType *,google::protobuf::Arena *)'
    1>          with
    1>          [
    1>              GenericType=google::protobuf::Message
    1>          ]

**Comment by toddwong** [comment] 2015-07-08 01:25
I'm sorry , I mess up the build configurations. The issue still there in release mode.

**Comment by zachc** [comment] 2015-07-09 00:21
Ah they seem to have reopened the ticket.

**Comment by amirrony** [comment] 2015-07-11 07:22
Hey,

Any fix or workaround for this problem?

How can I solve it for creating a release binary in VS 2015 (community)

**Comment by breathe67** [comment] 2015-07-11 18:18
No fix for me, for now just building protoc in debug mode, and
protobuf-lite in release mode...

**Comment by xfxyjwf** [comment] 2015-07-15 18:25
I agree with @pherl's assessment that this is probably a vs 2015 bug rather than a protobuf one. Although I haven't been able to reproduce the exact problem in a simple program, I suspect the issue is related to declaration of specification of class template member functions.

I mirrored the code structure of GenericTypeHandler with something like this:
<pre>
// foo.h
template<typename T> class Foo {
 public:
  static void Call() {}
};

template<>
void Foo<int>::Call();
</pre>

<pre>
// foo.cc
#include "foo.h"
template<>
void Foo<int>::Call() {}
</pre>

<pre>
#include "foo.h"
int main() { Foo<int>::Call(); }
</pre>

But when I tested the above program, it consistently fails with "Unresolved external symbol" error in both debug and release build. Not sure why protobuf code can still build debug build.

**Comment by Waty** [comment] 2015-07-20 16:28
Error is still occuring in the final release of VS2015 Enterprise

**Comment by ml232528** [comment] 2015-07-21 07:00
If such changes can be compiled through

modify message.h
#include "google/protobuf/repeated_field.h"
...
namespace internal {
	// Macro defined in repeated_field.h. We can only define the Message-specific
	// GenericTypeHandler specializations here because we depend on Message, which
	// is not part of proto2-lite hence is not available in repeated_field.h.
	DEFINE_SPECIALIZATIONS_FOR_BASE_PROTO_TYPES_NOINLINE(Message);
}  // namespace internal

}  // namespace protobuf

}  // namespace google
#endif  // GOOGLE_PROTOBUF_MESSAGE_H__



modify message.cc
//DEFINE_SPECIALIZATIONS_FOR_BASE_PROTO_TYPES_NOINLINE(Message);



9>  正在生成代码...
9>LINK : warning LNK4075: 忽略“/INCREMENTAL”(由于“/OPT:ICF”规范)
9>  tests.vcxproj -> D:\项目文件\google\protobuf-3.0.0-alpha-2\vsprojects\Release\tests.exe
========== 生成: 成功 9 个，失败 0 个，最新 0 个，跳过 0 个 ==========

**Comment by mloskot** [comment] 2015-08-05 13:50
I can reproduce the problem with  Visual Studio Professional 2015 (Version 14.0.23107.0 D14REL):
* x64 build
```
D:\dev\protobuf\protobuf.git\cmake\_build>"c:\Program Files (x86)\CMake\bin\cmake.exe" -G "Visual Studio 14 2015 Win64" -DBUILD_TESTING=OFF ..
-- The C compiler identification is MSVC 19.0.23026.0
-- The CXX compiler identification is MSVC 19.0.23026.0
-- Check for working C compiler using: Visual Studio 14 2015 Win64
-- Check for working C compiler using: Visual Studio 14 2015 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 14 2015 Win64
-- Check for working CXX compiler using: Visual Studio 14 2015 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: D:/dev/protobuf/protobuf.git/cmake/_build
```
* Debug builds with success
* Release fails at linking:
```
1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>  Checking Build System
1>  CMake does not need to re-run because D:/dev/protobuf/protobuf.git/cmake/_build/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: libprotobuf, Configuration: Release x64 ------
3>------ Build started: Project: libprotobuf-lite, Configuration: Release x64 ------
2>  Building Custom Rule D:/dev/protobuf/protobuf.git/cmake/CMakeLists.txt
2>  CMake does not need to re-run because D:\dev\protobuf\protobuf.git\cmake\_build\CMakeFiles\generate.stamp is up-to-date.
3>  Building Custom Rule D:/dev/protobuf/protobuf.git/cmake/CMakeLists.txt
3>  CMake does not need to re-run because D:\dev\protobuf\protobuf.git\cmake\_build\CMakeFiles\generate.stamp is up-to-date.
2>  arena.cc
3>  arena.cc
2>  arenastring.cc
3>  arenastring.cc
2>  extension_set.cc
3>  extension_set.cc
2>  generated_message_util.cc
3>  generated_message_util.cc
2>  coded_stream.cc
3>  coded_stream.cc
2>  zero_copy_stream.cc
3>  zero_copy_stream.cc
2>  zero_copy_stream_impl_lite.cc
3>  zero_copy_stream_impl_lite.cc
3>  message_lite.cc
2>  message_lite.cc
2>  repeated_field.cc
3>  repeated_field.cc
2>  atomicops_internals_x86_gcc.cc
3>  atomicops_internals_x86_gcc.cc
3>  atomicops_internals_x86_msvc.cc
2>  atomicops_internals_x86_msvc.cc
3>  bytestream.cc
2>  bytestream.cc
3>  common.cc
2>  common.cc
3>  once.cc
2>  once.cc
3>  status.cc
2>  status.cc
3>  statusor.cc
2>  statusor.cc
3>  stringpiece.cc
2>  stringpiece.cc
3>  stringprintf.cc
2>  stringprintf.cc
3>  strutil.cc
2>  strutil.cc
3>  time.cc
2>  time.cc
3>  Generating Code...
2>  Generating Code...
3>  Compiling...
3>  wire_format_lite.cc
2>  Compiling...
2>  wire_format_lite.cc
3>  Generating Code...
2>  any.cc
3>  libprotobuf-lite.vcxproj -> D:\dev\protobuf\protobuf.git\cmake\_build\Release\libprotobuf-lite.lib
2>  any.pb.cc
2>  api.pb.cc
2>  importer.cc
2>  parser.cc
2>  descriptor.cc
2>  descriptor.pb.cc
2>  descriptor_database.cc
2>  duration.pb.cc
2>  dynamic_message.cc
2>  empty.pb.cc
2>  extension_set_heavy.cc
2>  field_mask.pb.cc
2>  generated_message_reflection.cc
2>D:\dev\protobuf\protobuf.git\src\google\protobuf\generated_message_reflection.cc(2157): warning C4506: no definition for inline function 'google::protobuf::Message *google::protobuf::internal::GenericTypeHandler<google::protobuf::Message>::NewFromPrototype(const GenericType *,google::protobuf::Arena *)'
2>          with
2>          [
2>              GenericType=google::protobuf::Message
2>          ]
2>  gzip_stream.cc
2>  printer.cc
2>  strtod.cc
2>  tokenizer.cc
2>  zero_copy_stream_impl.cc
2>  Generating Code...
2>  Compiling...
2>  map_field.cc
2>  message.cc
2>  reflection_ops.cc
2>  service.cc
2>  source_context.pb.cc
2>  struct.pb.cc
2>  mathlimits.cc
2>  structurally_valid.cc
2>  substitute.cc
2>  text_format.cc
2>  timestamp.pb.cc
2>  type.pb.cc
2>  unknown_field_set.cc
2>  field_comparator.cc
2>  datapiece.cc
2>  default_value_objectwriter.cc
2>  error_listener.cc
2>  field_mask_utility.cc
2>  json_escaping.cc
2>  json_objectwriter.cc
2>  Generating Code...
2>  Compiling...
2>  json_stream_parser.cc
2>  object_writer.cc
2>  protostream_objectsource.cc
2>  protostream_objectwriter.cc
2>  type_info.cc
2>  type_info_test_helper.cc
2>  utility.cc
2>  json_util.cc
2>  message_differencer.cc
2>  type_resolver_util.cc
2>  wire_format.cc
2>  wrappers.pb.cc
2>  Generating Code...
2>  libprotobuf.vcxproj -> D:\dev\protobuf\protobuf.git\cmake\_build\Release\libprotobuf.lib
4>------ Build started: Project: libprotoc, Configuration: Release x64 ------
4>  Building Custom Rule D:/dev/protobuf/protobuf.git/cmake/CMakeLists.txt
4>  CMake does not need to re-run because D:\dev\protobuf\protobuf.git\cmake\_build\CMakeFiles\generate.stamp is up-to-date.
4>  code_generator.cc
4>  command_line_interface.cc
4>  cpp_enum.cc
4>  cpp_enum_field.cc
4>  cpp_extension.cc
4>  cpp_field.cc
4>  cpp_file.cc
4>  cpp_generator.cc
4>  cpp_helpers.cc
4>  cpp_map_field.cc
4>  cpp_message.cc
4>  cpp_message_field.cc
4>  cpp_primitive_field.cc
4>  cpp_service.cc
4>  cpp_string_field.cc
4>  csharp_enum.cc
4>  csharp_enum_field.cc
4>  csharp_field_base.cc
4>  csharp_generator.cc
4>  csharp_helpers.cc
4>  Generating Code...
4>  Compiling...
4>  csharp_map_field.cc
4>  csharp_message.cc
4>  csharp_message_field.cc
4>  csharp_primitive_field.cc
4>  csharp_repeated_enum_field.cc
4>  csharp_repeated_message_field.cc
4>  csharp_repeated_primitive_field.cc
4>  csharp_source_generator_base.cc
4>  csharp_umbrella_class.cc
4>  csharp_wrapper_field.cc
4>  java_context.cc
4>  java_doc_comment.cc
4>  java_enum.cc
4>  java_enum_field.cc
4>  java_enum_field_lite.cc
4>  java_extension.cc
4>  java_field.cc
4>  java_file.cc
4>  java_generator.cc
4>  java_generator_factory.cc
4>  Generating Code...
4>  Compiling...
4>  java_helpers.cc
4>  java_lazy_message_field.cc
4>  java_lazy_message_field_lite.cc
4>  java_map_field.cc
4>  java_map_field_lite.cc
4>  java_message.cc
4>  java_message_builder.cc
4>  java_message_builder_lite.cc
4>  java_message_field.cc
4>  java_message_field_lite.cc
4>  java_message_lite.cc
4>  java_name_resolver.cc
4>  java_primitive_field.cc
4>  java_primitive_field_lite.cc
4>  java_service.cc
4>  java_shared_code_generator.cc
4>  java_string_field.cc
4>  java_string_field_lite.cc
4>  javanano_enum.cc
4>  javanano_enum_field.cc
4>  Generating Code...
4>  Compiling...
4>  javanano_extension.cc
4>  javanano_field.cc
4>  javanano_file.cc
4>  javanano_generator.cc
4>  javanano_helpers.cc
4>  javanano_map_field.cc
4>  javanano_message.cc
4>  javanano_message_field.cc
4>  javanano_primitive_field.cc
4>  objectivec_enum.cc
4>  objectivec_enum_field.cc
4>  objectivec_extension.cc
4>  objectivec_field.cc
4>  objectivec_file.cc
4>  objectivec_generator.cc
4>  objectivec_helpers.cc
4>  objectivec_map_field.cc
4>  objectivec_message.cc
4>  objectivec_message_field.cc
4>  objectivec_oneof.cc
4>  Generating Code...
4>  Compiling...
4>  objectivec_primitive_field.cc
4>  plugin.cc
4>  plugin.pb.cc
4>  python_generator.cc
4>  ruby_generator.cc
4>  subprocess.cc
4>  zip_writer.cc
4>  Generating Code...
4>  libprotoc.vcxproj -> D:\dev\protobuf\protobuf.git\cmake\_build\Release\libprotoc.lib
5>------ Build started: Project: protoc, Configuration: Release x64 ------
5>  Building Custom Rule D:/dev/protobuf/protobuf.git/cmake/CMakeLists.txt
5>  CMake does not need to re-run because D:\dev\protobuf\protobuf.git\cmake\_build\CMakeFiles\generate.stamp is up-to-date.
5>  main.cc
5>libprotobuf.lib(generated_message_reflection.obj) : error LNK2019: unresolved external symbol "public: static class google::protobuf::Message * __cdecl google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message>::NewFromPrototype(class google::protobuf::Message const *,class google::protobuf::Arena *)" (?NewFromPrototype@?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@SAPEAVMessage@34@PEBV534@PEAVArena@34@@Z) referenced in function "private: void __cdecl google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInnerLoop<class google::protobuf::internal::GenericTypeHandler<class google::protobuf::Message> >(void * *,void * *,int,int)" (??$MergeFromInnerLoop@V?$GenericTypeHandler@VMessage@protobuf@google@@@internal@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@AEAAXPEAPEAX0HH@Z)
5>D:\dev\protobuf\protobuf.git\cmake\_build\Release\protoc.exe : fatal error LNK1120: 1 unresolved externals
6>------ Skipped Build: Project: ALL_BUILD, Configuration: Release x64 ------
6>Project not selected to build for this solution configuration 
========== Build: 4 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========
```

**Comment by Uli1** [comment] 2015-08-12 14:07
A quick and dirty hack for VS2015 x64 release build is to add another function implemetation into

generated_message_reflection.cc
...
namespace internal {
...
	template<>
		Message* GenericTypeHandler<Message>::NewFromPrototype(
			const Message* prototype, google::protobuf::Arena* arena) {
			return prototype->New(arena);
		}
...

**Comment by mloskot** [comment] 2015-08-20 10:21
Pull request #717 fixes this issue.

**Comment by DouglasHeriot** [comment] 2015-08-20 12:53
Ha, I didn’t even see this issue – yes my pull request #717 is a workaround for exactly this.

**Comment by DouglasHeriot** [comment] 2015-08-26 03:02
This should be fixed in pull request #726 – I marked just the problematic function as __declspec(noinline) if the compiler is VS ≥ 2015.

Can someone verify and close this issue?

**Comment by xfxyjwf** [comment] 2015-08-26 03:27
@TeBoring please help verify if it's working now for VS2015.

**Comment by 0xAAE** [comment] 2015-08-30 18:37
For now, I should add next 4 lines to message.cc file:
#if defined(_MSC_VER) && (_MSC_VER >= 1900)
// Note: force noinline to workaround MSVC 2015 compiler bug, issue #240
GOOGLE_ATTRIBUTE_NOINLINE
#endif

after template<> and before
google::protobuf::Arena* GenericTypeHandler<Message>::GetArena(

and after template<> and before
void* GenericTypeHandler<Message>::GetMaybeArenaPointer(

Theese methods are imediately after fixed in #726 Message* GenericTypeHandler<Message>::NewFromPrototype(...)

After this everything has built OK in MCVS 2015 Community Edition

**Comment by xfxyjwf** [comment] 2015-09-14 20:32
@0xAAE  could you help send us a pull request? The change you mentioned seems to be what's missing from @DouglasHeriot's original pull request #726

**Comment by 0xAAE** [comment] 2015-09-14 21:53
Certainly, I'll send. Please, explain me briefly how can I do it. Also, notice that only release build produce the errors, debug one is OK

**Comment by xfxyjwf** [comment] 2015-09-14 21:59
Thanks. You can follow the generate instructions on how to send pull requests:
https://help.github.com/articles/using-pull-requests/

Basically you first fork a protobuf branch under your github account, push your changes there, and create a pull request (a few simple clicks) to merge your branch to protobuf master branch.

**Comment by 0xAAE** [comment] 2015-09-14 22:04
Ok, I'll post here when finish

**Comment by 0xAAE** [comment] 2015-09-14 22:48
I've just done pull request

**Comment by xfxyjwf** [comment] 2015-09-16 21:47
I believe this issue is fixed now (thanks @DouglasHeriot and @0xAAE ).

**Closed** 2015-09-16 21:47 UTC
