### ISSUE TITLE
Can't use unbundled python protobuf on Linux if python-protobuf package is installed

### ISSUE THREAD

**Issue by primiano** [google/protobuf#1484] opened 2016-05-04 12:04 UTC
Here's the problem. On Ubuntu Linux Trusty, I have the python-protobuf package installed from apt.
Now, I am trying to use the python protobuf library from the sources (specifically form a chromium tree, but this is irrelevant) by prepending in the path. The problem is that the dist-package version of google.protobuf gets always picked first.
Repro:

> > > import sys
> > > sys.path.insert(0, '/s/chrome/src/third_party/protobuf/python')
> > > import google.protobuf
> > > google.protobuf
> > > <module 'google.protobuf' from '/usr/lib/python2.7/dist-packages/google/protobuf/**init**.pyc

I investigated a bit with a colleague and this seems to be due to the google/**init**.py
In v3.0.0-beta-2 it does:
_import__('pkg_resources').declare_namespace(**name**)

the problem seems to be that the corresponding debian site-package is a conventional module w/o namespace (i.e. /usr/lib/python2.7/dist-packages/google/protobuf/**init**.py is just empty)

Later 786f80fe6632902be74f90a577d75e8641494abd  changed that to 
try:
  **import**('pkg_resources').declare_namespace(**name**)
except ImportError:
  **path** = **import**('pkgutil').extend_path(**path**, **name**)

which does not really solve the problem.
The right resolution seems to follow what PEP420 suggests, namely:

> Namespace packages today
> Python currently provides pkgutil.extend_path to denote a package as a namespace package. The recommended way of using it is to put:
> from pkgutil import extend_path
> **path** = extend_path(**path**, **name**)

I confirm that this fixes the issue and makes protobuf sources usable as a module even in presence of the python-protobuf system package.

**Comment by primiano** [comment] 2016-05-04 12:45
@silviulica @craigcitro 
What is the rationale of the try / pkg_resources / except / pkgutil?
I'd go for https://github.com/primiano/protobuf/commit/ed07ef2fc2d55e192e4879c1d062b3886bfc6d5e
but I have no idea if I am breaking something and how to test it

setup.py is failing regardless for me on master:
```
$ python setup.py build
running build
running build_py
Generating google/protobuf/descriptor_pb2.py...
google/protobuf/descriptor.proto:386:3: Expected "required", "optional", or "repeated".
google/protobuf/descriptor.proto:386:12: Expected field name.

```

**Comment by craigcitro** [comment] 2016-05-04 16:27
@primiano We had originally wanted to go with just `pkgutil`, but had heard that trying `pkg_resources` first was the preferred approach. This is one where I know I'm in over my head -- @jonparrott, is there a reason to prefer `pkg_resources` over `pkgutil`?

**Comment by jonparrott** [comment] 2016-05-04 16:46
`pkg_resources` is from `setuptools` which does things better than `pkgutil`. Notably:

* it supports PEP 302, Import hooks.
* If an existing non-namespace package is in `sys.path` and different package is installed that says the first package is indeed a namespace package, then it'll fix the module's `__path__` correctly.
* Other black magic.

The real issue here is that no matter what you can not do a in-place upgrade of a package that once was not namespaced with a version that is now namespaced. The workaround is to have `setup.py` check for this situation and tell the user to uninstall the package first. Prior art [here](https://github.com/google/google-api-python-client/blob/master/setup.py#L51).

**Comment by craigcitro** [comment] 2016-05-04 17:02
Thanks @jonparrott! That was super helpful.

@primiano does removing the old package first work for you?

And to head off a potential question: we do still want the `pkgutil` fallback, for "exotic" environments where setuptools is not available. (Google's internal codebase is one such environment.)

**Comment by primiano** [comment] 2016-05-05 09:59
So stepping back a little, this is my concrete problem:
In the chrome codebase we have protobuf v3.0.0 ($CHROME/src/third_party/protobuf).
As part of the build I generate a python stub by doing protoc file.proto --python_out=somewhere, where protoc is built from $CHROME/src/third_party/protobuf. So far so good.

Now I would like to consume the generated file_pb2.py as part of the build process itself (i.e. run a python script which does "import file_pb2"). Clearly I want python to pick the protobuf python libs in $CHROME/src/third_party/protobuf/python, as the generated stub must match the runtime library (and concretely it fails if I don't, which is WAI).

Now, my problem is that if the developer has installed the python-protobuf package, I don't know any way to force python to pick $CHROME/src/third_party/protobuf/python instead of the dist-package. Which is bad++. How do I achieve this? I cannot ask chrome devs to uninstall system packages to build, that is unprecedented.

In general feels very weird to me that this python library cannot be imported without installing / uninstalling other stuff.
In this specific case If I prepend  $CHROME/src/third_party/protobuf/python as first element of the sys.path I do expect that library to be picked first. Instead, the dist-package is picked, inverting the order of what I requested.

I admit that I am ignorant about pkgutil vs pkg_resources. The only things that I can see is that:
- pkgutil does the right thing (w.r.t. properly setting up paths in presence of a dist google module)
- PEP420 reccomends pkgutil.
So my, perhaps naive, question here is: what is the disadvantage of pkgutil vs pkg_resources?

@jonparrott 
> The real issue here is that no matter what you can not do a in-place upgrade of a package that once was not namespaced with a version that is now namespaced.
No my real issue here is not about install. I am not trying to install anything. I just want to use the local protobuf library (which feels to me a reasonable requirement) and I don't see any way to achieve this.

> The workaround is to have setup.py check for this situation and tell the user to uninstall the package first.
I am not interested into running any setup.py here.

**Comment by jonparrott** [comment] 2016-05-05 18:20
> PEP420 recomends pkgutil. So my, perhaps naive, question here is: what is the disadvantage of pkgutil vs pkg_resources?

`pkgutil` is preferred if you need to support `.pkg` files, `pkg_resources` works better for all other cases.


> In this specific case If I prepend $CHROME/src/third_party/protobuf/python as first element of the sys.path I do expect that library to be picked first. Instead, the dist-package is picked, inverting the order of what I requested.

Manipulating `sys.path` is **bad**. People say it's bad and tell you not to do it for a reason. Python's import lookup system isn't as simple as checking directories. For protobuf, this is a "non-trivial" package that requires namespace packages to be setup - this happens as part of the site-packages initialization logic. There's ways to do this after interpreter startup (see darth-vendor which eventually made its way into appengine), but they aren't pretty and you shouldn't do them.

> No my real issue here is not about install. I am not trying to install anything. I just want to use the local protobuf library (which feels to me a reasonable requirement) and I don't see any way to achieve this.

Unfortunately, this isn't a reasonable request. This is a python library and it's designed to be installed to work. Even the tests install it first. This is how it works. Libraries only work without having their `setup.py` run in certain cases. You could try doing some wheel magic, but even that it too much black magic for this.

It seems like what you want to do is setup a virtualenv and install your custom version of protobuf into that, then use it.
```
$ virtualenv env
$ source env/bin/activate
$ pip install src/third_party/protobuf/python
```

**Comment by primiano** [comment] 2016-05-17 10:38
closing the loop, in case somebody encounters this in future.
I found this hack that seems to make things work without requiring folks to install virtualenv.

```
import os
_PROTOBUF_DIR = os.path.join(_CHROME_SRC, 'third_party', 'protobuf', 'python')
import pkg_resources
pkg_resources.declare_namespace('google')
pkg_resources.fixup_namespace_packages(_PROTOBUF_DIR)
import google
assert _PROTOBUF_DIR in google.__path__[0]
import google.protobuf
assert _PROTOBUF_DIR in google.protobuf.__path__[0]
import google.protobuf.descriptor
...

```

**Comment by acozzette** [comment] 2017-03-07 18:07
Let me go ahead and close this since it sounds like the problem is more-or-less resolved.

**Closed by acozzette** 2017-03-07 18:07 UTC
Labels: python
