### ISSUE TITLE
javascript code generator generates unused require of import weak

### ISSUE THREAD

**Issue by tamird** [google/protobuf#1703] opened 2016-06-22 16:24 UTC
In our protos, we `import weak "gogoproto/gogo.proto";` and use it for Golang-specific options. Using this proto with `--js_out`, an unused `var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');` is generated. I believe `import weak` should not result in a generated `require`.

cc @haberman

**Comment by xfxyjwf** [comment] 2016-06-22 17:42
What do you use "import weak" for? I don't think that's a supported feature in opensource protobuf and should be flagged as a compile error when you invoke protoc.

**Comment by tamird** [comment] 2016-06-22 20:59
Well, we've been using it for importing protos that are needed only for various field or message options (and not for any messages).

In other words, we need this proto during code generation of our other protos, but we don't want to have to codegen and compile it into the application.

**Comment by hl3w22bupt** [comment] 2016-07-20 11:13
I have this similar problem. I import the github.com/gogo/protobuf/gogoproto/gogo.proto and use it for Golang-specific options. but the generated cpp file has generated line #include "github.com/gogo/protobuf/gogoproto/gogo.pb.h"

**Comment by xfxyjwf** [comment] 2016-07-20 18:01
Regarding the imports/includes/requires, protoc is working as intended here. In JS/C++ or even Go, protoc should generate imports/includes/requires for the imported gogo.proto file. This is necessary for the custom options to be correctly interpreted at runtime for every language. Protoc has to assume the .proto file will be used at runtime for every language because it has no way to tell whether an import is used for a specific language, nor it can tell whether the imported .proto file is used at compile time only or both compile time and runtime.

We can probably add a new syntax to support language-specific compile-time custom options, but "import weak" is certainly not the right one. Also can you describe what problem does the additional include/require cause for you? Adding a new syntax is a big change and we need more supporting data for it.

**Comment by tamird** [comment] 2016-07-20 18:07
The main downside of additional imports is that we have to compile the
aforementioned file, which in the case of `gogo` is located out-of-tree.
Remember, we have to compile this thing even in JS, so now our JS tooling
needs to know about GOPATH.

**Comment by xfxyjwf** [comment] 2016-07-20 20:03
If dependency is an issue, I guess we can support the ability to trim down .proto dependencies as a standard feature of protoc, so you can tailor your .proto dependencies as you like.

**Comment by tamird** [comment] 2016-07-20 23:35
I don't understand what you're proposing concretely, but I think you
understand the problem, so if your solution addresses it then :+1:

**Comment by gerben-s** [comment] 2017-03-09 00:51
import weak is not an open source option. Closing this bug

**Closed by gerben-s** 2017-03-09 00:51 UTC
Labels: bug, protoc
