### ISSUE TITLE
3.0.0 compile error with gcc 5.4

### ISSUE THREAD

**Issue by glensc** [google/protobuf#2068] opened 2016-09-04 19:23 UTC
```
libtool: compile:  ccache g++ -DHAVE_CONFIG_H -I. -I.. -DGOOGLE_PROTOBUF_NO_RTTI -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -fwrapv -pipe -Wformat -Werror=format-security -gdwarf-4 -fno-debug-types-section -fvar-tracking-assignments -g2 -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC -march=x86-64 -gdwarf-4 -fno-debug-types-section -fvar-tracking-assignments -g2 -MT google/protobuf/descriptor.pb.lo -MD -MP -MF google/protobuf/.deps/descriptor.pb.Tpo -c google/protobuf/descriptor.pb.cc  -fPIC -DPIC -o google/protobuf/.libs/descriptor.pb.o 
In file included from google/protobuf/stubs/mathlimits.cc:36:0: 
./google/protobuf/stubs/mathlimits.h:203:315: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:203:315: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:203:315: error: overflow in constant expression [-fpermissive] 
In file included from google/protobuf/stubs/mathlimits.cc:36:0: 
./google/protobuf/stubs/mathlimits.h:204:330: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:204:330: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:204:330: error: overflow in constant expression [-fpermissive] 
In file included from google/protobuf/stubs/mathlimits.cc:36:0: 
./google/protobuf/stubs/mathlimits.h:205:312: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:205:312: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:205:312: error: overflow in constant expression [-fpermissive] 
In file included from google/protobuf/stubs/mathlimits.cc:36:0: 
./google/protobuf/stubs/mathlimits.h:206:327: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:206:327: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:206:327: error: overflow in constant expression [-fpermissive] 
In file included from google/protobuf/stubs/mathlimits.cc:36:0: 
./google/protobuf/stubs/mathlimits.h:207:342: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:207:342: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:207:342: error: overflow in constant expression [-fpermissive] 
In file included from google/protobuf/stubs/mathlimits.cc:36:0: 
./google/protobuf/stubs/mathlimits.h:208:320: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:208:320: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:208:320: error: overflow in constant expression [-fpermissive] 
In file included from google/protobuf/stubs/mathlimits.cc:36:0: 
./google/protobuf/stubs/mathlimits.h:209:335: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:209:335: error: overflow in constant expression [-fpermissive] 
./google/protobuf/stubs/mathlimits.h:209:335: error: overflow in constant expression [-fpermissive] 
make[2]: *** [Makefile:3874: google/protobuf/stubs/mathlimits.lo] Error 1 
```

```
➔ gcc --version
gcc (PLD-Linux) 5.4.0 20160603 (release)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by glensc** [comment] 2016-09-04 19:24
full build log if neccessary: http://carme.pld-linux.org/~glen/protobuf-2068.log

**Comment by glensc** [comment] 2016-09-04 19:26
errors related to these lines in source tree:
https://github.com/google/protobuf/blob/v3.0.0/src/google/protobuf/stubs/mathlimits.h#L203-L209

**Comment by acozzette** [comment] 2017-12-13 23:06
I'm going to close this issue because I haven't been able to reproduce it even with gcc 5.4 on godbolt.org. Feel free to reopen it if this is still a problem, though.

**Closed by acozzette** 2017-12-13 23:06 UTC
Labels: bug, c++

**Comment by HarborDong** [comment] 2020-10-22 17:40
i encounter the same issue.
OS:ubuntu 16.04
gcc:5.4
compile log:
protobuf/src/google/protobuf/stubs/mathlimits.h:143:79: error: overflow in constant expression [-fpermissive]
   (((Type(1) << (sizeof(Type)*8 - 1)) - 1) + (Type(1) << (sizeof(Type)*8 - 1)))
