### ISSUE TITLE
[Bug] Setting parcelable_messages = true in JavaNano, is not package com.google.protobuf.nano.android

### ISSUE THREAD

**Issue by MartinDong** [google/protobuf#2479] opened 2016-12-10 04:00 UTC
As per https://github.com/google/protobuf/tree/master/javanano, setting the "parcelable_messages" option as "true" should make the generated messages parcelable within the context of Android. However, setting that option as "true" results in errors stating
"error: package com.google.protobuf.nano.android does not exist"
on these types

``` java
com.google.protobuf.nano.android.ParcelableMessageNano
com.google.protobuf.nano.android.ParcelableMessageNanoCreator
```
in the protobuf gradle plugin generated java file within Android Studio.

Adding the

com.google.protobuf.nano:protobuf-javanano:3.1.0
artifact as a compile type dependency does not seem to resolve the error

**Comment by kurtisnelson** [comment] 2017-02-14 19:29
Dupe of #956

**Closed** 2017-02-14 21:50 UTC
Labels: wontfix
