### ISSUE TITLE
Ruby 2.4.4 Alpine 3.7 grpc 1.12 seg fault error

### ISSUE THREAD

**Issue by carlpartridge** [google/protobuf#4728] opened 2018-06-05 14:11 UTC
### What version of protobuf and what language are you using?
grpc (1.12.0)
google-protobuf (3.5.1.2)
ruby 2.4.4
 
### What operating system (Linux, Windows, …) and version?
 Alpine 3.7
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 In dockerfile we RUN apk --update ... add ... gcc ...
(full dockerfile below)
 
### What did you do?
Spinning up a kubernetes cluster and the rails app within a pod is crashing on startup:
```
/usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc/grpc.rb:20:in `require_relative': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc/2.4/grpc_c.so) - /usr/local/bundle/gems/grpc-1.12.0-x86_64-linux/src/ruby/lib/grpc/2.4/grpc_c.so (LoadError)
```

There was an old fix I found on google that said to add the libc6-compat to the dockerfile, that seems to fix the above issue but now throws a seg fault in protobuf:

```
/usr/local/bundle/gems/google-protobuf-3.5.1.2-x86_64-linux/lib/google/protobuf/any_pb.rb:15: [BUG] Segmentation fault at 0x0000000000016e16
c:0137 p:---- s:0671 e:000670 CFUNC :msgclass
c:0134 p:0039 s:0661 E:001800 TOP /usr/local/bundle/gems/google-protobuf-3.5.1.2-x86_64-linux/lib/google/protobuf/any_pb.rb:13 [FINISH]
c:0136 p:0026 s:0667 e:000666 CLASS /usr/local/bundle/gems/google-protobuf-3.5.1.2-x86_64-linux/lib/google/protobuf/any_pb.rb:15
 ```

### What did you expect to see?
 No errors
 
### What did you see instead?
 See above
 
### Anything else we should know about your project / environment?
I assume the issue is in the Alpine build but this is all way out of my league.  We have google-cloud-pubsub working with the same app in production environments on a google cloud ubuntu VM and we have the app working in production in a kubernetes cluster with the google-cloud-pubsub gem installed but not called anywhere.  Any help is appreciated!

Here is the full dockerfile:
```
FROM ruby:2.4.4-alpine3.7

ENV RAILS_ROOT /rails/prism
ENV PAGER=/usr/bin/less
RUN mkdir -p $RAILS_ROOT/tmp/pids
WORKDIR $RAILS_ROOT
ADD Gemfile* ./

RUN apk --update --no-cache add bash mysql-dev mysql-client nodejs libxslt-dev libxml2-dev gcc g++ libcurl curl-dev pdftk poppler-utils
RUN apk --update add --virtual build-dependencies build-base build-dependencies gcc git less \
    && bundle install --jobs `expr $(cat /proc/cpuinfo | grep -c "cpu cores") - 1` --retry 3 --without test development\
    && apk del build-dependencies

COPY . $RAILS_ROOT

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
```

**Comment by TeBoring** [comment] 2018-06-25 19:35
duplicate of #4460

**Closed by TeBoring** 2018-06-25 19:35 UTC
Labels: bug, ruby
