### ISSUE TITLE
Getting Compilation error in protobuf 3.0.0 beta-1

### ISSUE THREAD

**Issue by bijaya012** [google/protobuf#1035] opened 2015-12-09 12:46 UTC
I am getting below compilation error.
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -MT google/protobuf/dynamic_message.lo -MD -MP -MF google/protobuf/.deps/dynamic_message.Tpo -c google/protobuf/dynamic_message.cc  -fPIC -DPIC -o google/protobuf/.libs/dynamic_message.o
./google/protobuf/stubs/hash.h: In instantiation of 'google::protobuf::hash<long long int>':
./google/protobuf/map.h:839:   instantiated from here
./google/protobuf/stubs/hash.h:269: error: invalid use of undefined type 'struct std::tr1::hash<long long int>'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional:1101: error: declaration of 'struct std::tr1::hash<long long int>'
./google/protobuf/map.h: In member function 'size_t google::protobuf::hashgoogle::protobuf::MapKey::operator()(const google::protobuf::MapKey&) const':
./google/protobuf/map.h:839: error: no match for call to '(google::protobuf::hash<long long int>) (google::protobuf::int64)'
./google/protobuf/stubs/hash.h: At global scope:
./google/protobuf/stubs/hash.h: In instantiation of 'google::protobuf::hash<long long unsigned int>':
./google/protobuf/map.h:843:   instantiated from here
./google/protobuf/stubs/hash.h:269: error: invalid use of undefined type 'struct std::tr1::hash<long long unsigned int>'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/tr1/functional:1101: error: declaration of 'struct std::tr1::hash<long long unsigned int>'
./google/protobuf/map.h: In member function 'size_t google::protobuf::hashgoogle::protobuf::MapKey::operator()(const google::protobuf::MapKey&) const':
./google/protobuf/map.h:843: error: no match for call to '(google::protobuf::hash<long long unsigned int>) (google::protobuf::uint64)'
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::Swap(google::protobuf::internal::MapFieldLite<Key, T, kKeyFieldType, kValueFieldType, default_enum_value>_)':
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:335: error: from this location
./google/protobuf/map_field.h:149: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::state_'
./google/protobuf/map_field_inl.h:337: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SetEntryDescriptor(const google::protobuf::Descriptor__)':
./google/protobuf/map_field.h:144: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::entry_descriptor_'
./google/protobuf/map_field_inl.h:348: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SetAssignDescriptorCallback(void (_)())':
./google/protobuf/map_field.h:145: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::assign_descriptor_callback_'
./google/protobuf/map_field_inl.h:358: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SyncRepeatedFieldWithMapNoLock() const':
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:388: error: from this location
./google/protobuf/map_field.h:137: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::arena_'
./google/protobuf/map_field_inl.h:389: error: from this location
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:390: error: from this location
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:392: error: from this location
./google/protobuf/map_field.h:137: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::arena_'
./google/protobuf/map_field_inl.h:394: error: from this location
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:400: error: from this location
./google/protobuf/map_field.h:137: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::arena_'
./google/protobuf/map_field_inl.h:409: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SyncMapWithRepeatedFieldNoLock() const':
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:426: error: from this location
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:427: error: from this location
./google/protobuf/map_field.h: In member function 'int google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::SpaceUsedExcludingSelfNoLock() const':
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:448: error: from this location
./google/protobuf/map_field.h:138: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::repeated_field_'
./google/protobuf/map_field_inl.h:449: error: from this location
./google/protobuf/map_field.h: In member function 'void google::protobuf::internal::MapField<Key, T, key_wire_type, value_wire_type, default_enum_value>::InitDefaultEntryOnce() const':
./google/protobuf/map_field.h:144: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::entry_descriptor_'
./google/protobuf/map_field_inl.h:471: error: from this location
./google/protobuf/map_field.h:144: error: object missing in reference to 'google::protobuf::internal::MapFieldBase::entry_descriptor_'
./google/protobuf/map_field_inl.h:474: error: from this location
make[2]: **\* [google/protobuf/dynamic_message.lo] Error 1

Please help me to build protobuf-3.0.0

Thanks.

**Comment by kilmarnock** [comment] 2015-12-15 14:35
same problem here, using current version (checkout minutes ago). Did you find a solution?

**Comment by xfxyjwf** [comment] 2016-01-07 03:16
It seems the hash configuration in the google/protobuf/stubs/hash.h file does not work properly for your platform. It might be that your platform hasn't been taken into consideration in the #ifdef #else ... branches. Could you help provide a fix that works for your targeted platform?

See the hash definition for std::tr1 here:
https://github.com/google/protobuf/blob/d8b6452e37b3f9e4341569ec74f8c3ca61e82b69/src/google/protobuf/stubs/hash.h#L144

**Comment by mger1** [comment] 2016-01-21 10:52
The problem is that GCC 4.1 has no std::tr1:hash for int64 types.

See:
http://stackoverflow.com/questions/14285019/gcc-4-1-1-doesnt-compile-some-code-with-tr1unordered-map

The other problems ("object missing in reference to...") can be fixed by adding an explicit "this->".

**Comment by matthauck** [comment] 2016-08-03 00:39
Seeing these errors myself on gcc 4.1.2. Put up a PR for the MapFieldBase errors. But, I have no idea quite where to go with the `std::tr1::hash< long long int >` not being present on this platform. 

Any clues on what can be done to resolve this? Perhaps some functionality can be disabled on these older platforms?

**Comment by matthauck** [comment] 2016-08-03 00:56
Actually, the only place this is used is for 64-bit map keys (fails for both uint64 and int64). I think I will put up another PR to just `#define` out these map key types on gcc 4.1.

**Comment by jianqiangyao** [comment] 2016-08-29 12:07
same problem, how to solve this?

**Comment by matthauck** [comment] 2017-03-02 18:24
I think this can be marked as closed now.

**Closed** 2017-03-08 00:18 UTC
Labels: bug, c++, help wanted
