### ISSUE TITLE
Travis iOS tests randomly crash

### ISSUE THREAD

**Issue by TeBoring** [google/protobuf#1232] opened 2016-02-12 22:09 UTC
Travis ios tests may randomly fail:
https://travis-ci.org/google/protobuf/jobs/108690120 [ UtilitiesTests testTextFormat ]
https://travis-ci.org/google/protobuf/jobs/108688571 [ WireFormatTests testSerialization ]
These failures cannot be reproduced locally.

**Comment by TeBoring** [comment] 2016-02-12 22:09
@thomasvl

**Comment by thomasvl** [comment] 2016-02-16 14:56
fyi - I've run the tests for iOS and OS X under: Address Sanitizer, Zombie Object, Guard Malloc, Guard Malloc Edges, and Malloc Scribble.  None of them have found any issues.

**Comment by thomasvl** [comment] 2016-02-16 14:58
Under the hood we use xctool to drive the OS X builds.  Looks like 0.2.8 got release right around when things start randomly failing.  Looking to see what changed.

**Comment by pgrosu** [comment] 2016-02-16 15:23
Hi Paul and Thomas,

I totally missed this issue while submitting the https://github.com/google/protobuf/issues/1242, which seems to have parallels to this.  It also contains the complete local Mac test.  For my local test, I got `xctool` via `brew`, who's Github source repository is here:

https://github.com/facebook/xctool

The version seemed to have been recently bumped - in the following commit - to `0.2.9` on Github for the next release, but not yet available:

https://github.com/facebook/xctool/commit/32fc52b67f025e7ba14489bafb3cf4c7910c1e02

I would be happy to help out with troubleshooting this.

Paul

**Comment by thomasvl** [comment] 2016-02-16 15:30
0.2.8 just got released the other week and looking at logs, it seems as soon as 0.2.8 started installing we're seeing the flake for iOS tests.  Doing some quick searching, I'm not seeing other folks complaining about this, but at the moment, I'm starting to think xctool is the cause.

I've got a pull running through travis right now to bump up the Xcode version we're also using (incase that helps xctool).  Locally I'm also playing with some new args (-newSimulatorInstance) to xctool to see if that helps any.

If you've got other ideas, I'm all ears.

**Comment by thomasvl** [comment] 2016-02-16 16:22
PR #1245 is tweaking the iOS run a little more, we'll see how it does for reference also.

**Comment by thomasvl** [comment] 2016-02-16 16:45
Looking at the logs some more, there isn't a completely clear pattern.  They have all run some times without issue.  When they do fail, it usually is in the last two destinations; some times the iPad Air others the iPad 2.  There also doesn't seem to be a pattern for Debug vs. Release.

**Comment by pgrosu** [comment] 2016-02-16 18:39
Hi Thomas and Paul,

Sorry to reply so late, as I was in another meeting.  Thank you Thomas for pointing me to this:

https://docs.travis-ci.com/user/languages/objective-c

I just downloaded the following for Xcode 7.2.1 via `Xcode -> Preferences -> Downloads`:

```
iOS 9.1 Simulator
iOS 9.0 Simulator
iOS 8.4 Simulator
iOS 8.3 Simulator
iOS 8.2 Simulator
iOS 8.1 Simulator
tvOS 9.0 Simulator
```

Then I reran the local test based PR #1245 to recover the errors, in order to have a starting point for troubleshooting:

Local Test for #1245
---------------------------------

```Bash
$ curl https://codeload.github.com/thomasvl/protobuf/zip/30e645b6b672673e28ae6cb24be92cc8de040554 -o protobuf-1245.zip
$ mkdir google
$ cd google
$ unzip ../protobuf-1245.zip
$ mv protobuf-30e645b6b672673e28ae6cb24be92cc8de040554 protobuf-1245
$ cd protobuf-1245
$ git checkout -qf FETCH_HEAD
$ chmod +x travis.sh
$ export CONFIG=objectivec_ios
$ export CXX=g++
$ export CC=gcc
$ g++ --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix

$ ./travis.sh $CONFIG
```

Local Tail Output for #1245
---------------------------

Below shows that the test concluded successfully:

```Bash

** RUN-TESTS SUCCEEDED: 788 passed, 0 failed, 0 errored, 788 total ** (7200 ms)

```

For the complete output, below is the download link:

[Local-Log-for-1245.txt](https://www.dropbox.com/s/a8dbouqq3na6wtb/Local-Log-for-1245.txt?dl=1)

Based on the above outputs I recommend that Travis be updated, which I think #1244 is part of the process - though that one is still failing, which could mean the packages might be out of date.  Can we request a custom Travis instance?

Paul

**Comment by thomasvl** [comment] 2016-02-16 18:48
Not sure what you mean by a custom instance for Travis.

If you check the travis history, you'll see that the iOS tests do pass some of the time.  Travis does run on a VM, there could be some timing bug inside this new xctool release that is causing the flake.  Running locally, we all might not see it because we're getting different timing.

**Comment by thomasvl** [comment] 2016-02-16 19:29
Just merged in PR #1245.  I was green on the PR build, but given this wasn't always failing, that doesn't mean anything.  We'll have to see how this goes with time and see if anyone has other ideas that might help.

**Comment by pgrosu** [comment] 2016-02-16 19:52
So what I think is that the environment might not be clean, but I'm willing to listen and try what you suggest :)  We could run the tests by trying out options from under `run-tests` (i.e. `-freshSimulator`, etc.), but before that let's test the timing idea out as follows:

1) Update the `travis.sh` script to download [cpulimit](https://github.com/opsengine/cpulimit) and compile it locally.  Then copy that in the root protobuf directory.

2) Then prepend the `xctool` to launch via `cpulimit` - below is an example that will run at 10% of how much the process would actually run at:

```Bash
$ ./cpulimit -l 10 xctool -configuration Debug -project objectivec/ProtocolBuffers_iOS.xcodeproj -scheme ProtocolBuffers -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 4s,OS=8.1' run-tests
```
If this works then we know it's the timing issue.  Can we just log into the Travis VM and run specific tests manually, to determine the optimal value?

Paul

**Comment by thomasvl** [comment] 2016-02-16 19:59
You're welcome to give cpulimit a try, but I'd be surprised if it actually does what you want in this case.  xctool is spawning all sorts of things along the way, and eventually causes the iOS simulator to run.  I haven't checked the code in a while, but if they actually get the simulator running via launch services or the Dock (NSWorkspace) (what is common on OS X), then there is no process inheritance that cpulimit could use to control that spawned process.

**Comment by pgrosu** [comment] 2016-02-16 20:23
I'm not sure I have that kind of access, but let's try a simpler test, which will break up the logic/app test size and also provide a clean simulator for each test as follows - I added `-logicTestBucketSize 1 -appTestBucketSize 1 -freshInstall -resetSimulator` at the end:

```
 xctool -configuration Debug -project objectivec/ProtocolBuffers_iOS.xcodeproj -scheme ProtocolBuffers -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 4s,OS=8.1' run-tests -logicTestBucketSize 1 -appTestBucketSize 1 -freshInstall -resetSimulator
```

If you could give this a test run and see if it works, this will will tell us if the VM is getting overwhelmed when the tests are being run.

Thank you,
Paul

**Comment by thomasvl** [comment] 2016-02-16 20:28
fyi - you can test that yourself via a PR, or you can do what I've done in the past: just fork the project and enable travis in your fork.  Just disable the linux tests in the .travis.yml file (since multi os support isn't enabled for everyone).  Then you can test away in your fork to try different things.

(testing it yourself is likely faster then cycling here and having me try things.)  :)

**Comment by pgrosu** [comment] 2016-02-16 20:33
I understand, but the issue is that I cannot sign the CLA but am willing to help out :)

**Comment by pgrosu** [comment] 2016-02-17 08:23
I'm giving it a try via https://github.com/google/protobuf/pull/1249, and will close it afterwards :)

**Comment by thomasvl** [comment] 2016-02-18 03:51
Looks like iOS timed out.  Oddly, it seems like you got the failure in the OS X build.  That's the first I've seen that happen, and I still can't make it happen with any of the Xcode debugging support.

**Comment by pgrosu** [comment] 2016-02-18 07:04
Now that we know how to slow it down, I'm wondering if the OS X build crash could be due to multiple VMs running on the same compute node, where one is bottlenecking the other.  The reason I am saying this, is because I'm seeing different `hostname: worker-jupiter-brain:` values for each build and in the past I sometimes saw two builds running at the same time.  I am not sure of the precise physical and VM setups of Travis - to optimize it properly - but we can infer by the tests below regarding settings that should work.

I was experimenting locally on my Mac, and the parameter that most affects the testing time seems to be `appTestBucketSize`.  So before we try an exponential progression for this parameter, let's try increasing it with the scope of slightly surpassing the lower bound that would allow all tests to at least complete.  Afterwards we can fine-tune it from there.  I am suggesting probably `50` would be a good starting point, and after that we can play with an exponential progression such as this:

| Round | Value `= 0.7*(Round^1.8)` |
| :---: | :---: |
|    1  |             1         |
|    2  |             2         |
|    3  |             5         |
|    4  |             8         |
|    5  |             13        |
|    6  |             18        |
|    7  |             23        |
|    8  |             30        |
|    9  |             37        |
|    10 |             44        |
|    11 |             52        |
|    12 |             61        |

So how about starting with `-appTestBucketSize 50` for now, and keep increasing it using the table above until we get all the tests to finish.  For this would you like me to update #1249, and then you can re-start the build?  

Let me know what you think.

Thanks,
Paul

**Comment by thomasvl** [comment] 2016-02-18 13:14
Sure, got for it.

I'm still torn here, since it seems like we're sorta showing something odd is happening on the VMs, so just limiting the number of tests in a run is just sorta hacking around the problem, nothing actually says it will avoid the problem, since it seems to be semi random it can still happen.

I spent a while last night running the tests locally against under the Address Sanitizer, Zombie Object, Guard Malloc, Guard Malloc Edges, and Malloc Scribble; all with no luck.  Also hacked things up to run a bunch of the tests in a loop under those to stress things, and still didn't get things to fail.

It may be time to contact support to see if they have seen problems like this before or if there is a bad VM or machines out there.

**Comment by thomasvl** [comment] 2016-02-18 13:41
Actually, just for kicks, I disabled the update of xctool to see if things pass/fail, and will run that a few times. https://travis-ci.org/thomasvl/protobuf/builds/110123901

**Comment by thomasvl** [comment] 2016-02-18 14:54
And the first run passes…I'll run a few more and if it keeps passing I guess I'll open an issue against xctool

**Comment by thomasvl** [comment] 2016-02-18 15:34
Running locally via xctool (trunk from Tuesday), I can still get the failures, but if I use xcodebuild or build from the Xcode UI, no failures.  Syncing xctool trunk to today, they stop.  There are two merges that seem to have landed since my Tuesday pull; so maybe that fixed things?  I'll play with this a little more and then open and issue for xctool.

**Comment by pgrosu** [comment] 2016-02-18 15:36
That sounds reasonable, and the test seems to suggest that it might be xctool that is causing this.  I'm sure you're probably already running this, but it would be nice to test the complete set of builds (c#, java, etc.) with the xctool update disabled.  This way we know it's not the VMs and that for builds that use xctool, version 0.2.7 still works after the bump to Xcode 7.2.

**Comment by thomasvl** [comment] 2016-02-18 15:45
I think I found it - https://github.com/facebook/xctool/issues/619.

Following that and some of the linked things off there seems to match what we see.  And the fix just landing is matching what I'm seeing locally with master.  Just asked if they have a 0.2.9 release planned with the fix.

**Comment by pgrosu** [comment] 2016-02-18 15:49
Just saw your new posts.  I recommend that if it works with 0.2.7, then it would probably be better to stay with that version for now.  Less than one day does not make me comfortable to ensure a tool works under all required scenarios/tests.  I prefer to vet it over a longer period of time, which would give us time to understand all the nuances of what was updated, and their impact of how those code changes scale up - which we could perform on a staging server.

**Comment by thomasvl** [comment] 2016-02-18 15:49
The python_cpp tests are failing because the newer Xcode image uses OS X 10.11, and the way the test is trying to load the library runs into the new security restrictions, I'm also talking to Josh about that.

**Comment by thomasvl** [comment] 2016-02-18 17:15
Spun python_cpp issue out into https://github.com/google/protobuf/issues/1253

**Closed** 2016-02-18 18:12 UTC
Labels: objective-c
