### ISSUE TITLE
Why removed protobuf v3.5.0?

### ISSUE THREAD

**Issue by jianghuaw** [google/protobuf#3942] opened 2017-11-23 06:07 UTC
Can anyone help to share the reason why v3.5.0 is gone? Due the removing, the OpenStack CI are failing with the same error:
e.g. http://dd6b71949550285df7dc-dda4e480e005aaa13ec303551d2d8155.r49.cf1.rackcdn.com/07/522407/1/check/dsvm-tempest-neutron-network/eb1ed94/logs/devstacklog.txt.gz

 2017-11-22 23:44:28.200 |   Could not find a version that satisfies the requirement protobuf===3.5.0 (from -c /opt/stack/new/requirements/upper-constraints.txt (line 338)) (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0, 3.1.0, 3.1.0.post1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0, 3.3.0, 3.4.0, 
 3.5.0.post1)

**Comment by ianychoi** [comment] 2017-11-23 08:33
I see also DevStack install failure on my local test now.

Github releases page ( https://github.com/google/protobuf/releases ) describes that Protobuf 3.5.0 released 10 days ago. However, I cannot find any other protobuf==3.5.0 with pip command: https://pypi.python.org/pypi/protobuf .

I am not sure who manages protobuf releases but maybe @pherl would help on it, or would someone share the details on protobuf 3.5.0.post1 version: https://pypi.python.org/pypi/protobuf/3.5.0.post1 ?

**Comment by pherl** [comment] 2017-11-24 03:25
Sorry for the breakage. The 3.5.0 release had regression on the service reflection which was fixed in 3.5.0.post1. Please depend on that instead.

I'd recommend specify dependency as version range on the minor version. in this case:  "protobuf>=3.5.0,<3.6.0".

**Closed by pherl** 2017-11-24 03:25 UTC

**Comment by taion** [comment] 2017-11-24 06:09
@pherl That's fine, but it's also best practice to lock down dependencies to get reproducible builds, and while bugs are unavoidable, completely breaking builds is much worse. I'm going to open an issue with PyPI, but in fact many package managers now make it impossible to unpublish versions exactly to avoid issues such as with `left-pad` in the npm ecosystem: http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy.

**Comment by taion** [comment] 2017-11-24 06:16
I opened an issue against PyPI in https://github.com/pypa/pypi-legacy/issues/738.

**Comment by jharbott** [comment] 2017-11-24 09:10
@pherl If you do a bugfix release, why is a not called 3.5.1?

**Comment by jianghuaw** [comment] 2017-11-24 16:39
@pherl Thanks for the clarification.
@taion that's a good idea to add policies to restrict deleting package in PyPI. I think we can deprecate a release with a new release if need some critical fixes instead of un-publishing a recently published release.

**Comment by eaglo** [comment] 2017-11-26 16:37
it also seems like a lot of wheels are "missing" :/
https://pypi.python.org/pypi/protobuf/3.5.0.post1

**Comment by taion** [comment] 2017-11-27 20:25
Well, the wheels are there now. This broke my build again, though, since the packages now end up resolving to new hashes, and my `Pipfile.lock` didn't include those hashes.
