### ISSUE TITLE
[Python] Source dist does not seem to match cp27 binary

### ISSUE THREAD

**Issue by dmtucker** [google/protobuf#2728] opened 2017-02-17 00:01 UTC
Setup:
```
dtucker@dtucker-wkstn:/tmp $ git clone git@github.west.isilon.com:eng-hdfs/pydoofus.git
...
dtucker@dtucker-wkstn:/tmp $ cd pydoofus/
```
If I install the bdist (`cp27`), I get an error:
```
dtucker@dtucker-wkstn:/tmp/pydoofus $ virtualenv venv-binary
...
dtucker@dtucker-wkstn:/tmp/pydoofus $ source  venv-binary/bin/activate
(venv-binary)dtucker@dtucker-wkstn:/tmp/pydoofus $ pip install --upgrade pip
...
(venv-binary)dtucker@dtucker-wkstn:/tmp/pydoofus $ pip install --only-binary cp27 protobuf
Collecting protobuf
  Downloading http://artifactory.west.isilon.com/artifactory/api/pypi/pypi-repo/packages/0f/53/e43b226f83a5a542c16695e9624b7bd2bde4ad016776c7c3233901bcf5b4/protobuf-3.2.0-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.6MB 65.7MB/s 
Collecting six>=1.9 (from protobuf)
  Downloading http://artifactory.west.isilon.com/artifactory/api/pypi/pypi-repo/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./venv-binary/lib/python2.7/site-packages (from protobuf)
Installing collected packages: six, protobuf
Successfully installed protobuf-3.2.0 six-1.10.0
(venv-binary)dtucker@dtucker-wkstn:/tmp/pydoofus $ python setup.py build
...
(venv-binary)dtucker@dtucker-wkstn:/tmp/pydoofus $ pip install .
...
(venv-binary)dtucker@dtucker-wkstn:/tmp/pydoofus $ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydoofus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydoofus/__init__.py", line 8, in <module>
    from . import namenode
  File "pydoofus/namenode/__init__.py", line 4, in <module>
    from . import v7
  File "pydoofus/namenode/v7.py", line 7, in <module>
    import pydoofus.protobuf.v7 as protobuf
  File "pydoofus/protobuf/__init__.py", line 1, in <module>
    from . import v7
  File "pydoofus/protobuf/v7/__init__.py", line 8, in <module>
    from . import RpcPayloadHeader_pb2 as RpcPayloadHeader
  File "pydoofus/protobuf/v7/RpcPayloadHeader_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x16RpcPayloadHeader.proto\"q\n\x15RpcPayloadHeaderProto\x12\x1e\n\x07rpcKind\x18\x01 \x01(\x0e\x32\r.RpcKindProto\x12(\n\x05rpcOp\x18\x02 \x01(\x0e\x32\x19.RpcPayloadOperationProto\x12\x0e\n\x06\x63\x61llId\x18\x03 \x02(\r\"f\n\x16RpcResponseHeaderProto\x12\x0e\n\x06\x63\x61llId\x18\x01 \x02(\r\x12\x1f\n\x06status\x18\x02 \x02(\x0e\x32\x0f.RpcStatusProto\x12\x1b\n\x13serverIpcVersionNum\x18\x03 \x01(\r*J\n\x0cRpcKindProto\x12\x0f\n\x0bRPC_BUILTIN\x10\x00\x12\x10\n\x0cRPC_WRITABLE\x10\x01\x12\x17\n\x13RPC_PROTOCOL_BUFFER\x10\x02*i\n\x18RpcPayloadOperationProto\x12\x15\n\x11RPC_FINAL_PAYLOAD\x10\x00\x12\x1c\n\x18RPC_CONTINUATION_PAYLOAD\x10\x01\x12\x18\n\x14RPC_CLOSE_CONNECTION\x10\x02*3\n\x0eRpcStatusProto\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\t\n\x05\x46\x41TAL\x10\x02')
  File "/tmp/pydoofus/venv-binary/local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 824, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "RpcPayloadHeader.proto":
  SUCCESS: "SUCCESS" is already defined in file "datatransfer.proto".
  SUCCESS: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "SUCCESS" must be unique within the global scope, not just within "RpcStatusProto".
  ERROR: "ERROR" is already defined in file "datatransfer.proto".
  ERROR: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "ERROR" must be unique within the global scope, not just within "RpcStatusProto".

>>> 
```
```
(venv-binary)dtucker@dtucker-wkstn:/tmp/pydoofus $ deactivate 
```
If I use the sdist, no error:
```
dtucker@dtucker-wkstn:/tmp/pydoofus $ virtualenv venv-source
...
dtucker@dtucker-wkstn:/tmp/pydoofus $ source venv-source/bin/activate
(venv-source)dtucker@dtucker-wkstn:/tmp/pydoofus $ pip install --upgrade pip
...
(venv-source)dtucker@dtucker-wkstn:/tmp/pydoofus $ pip install --no-use-wheel protobuf
DEPRECATION: --no-use-wheel is deprecated and will be removed in the future.  Please use --no-binary :all: instead.
Collecting protobuf
  Downloading http://artifactory.west.isilon.com/artifactory/api/pypi/pypi-repo/packages/e0/2f/690a5f047e2cfef40c9c5eec0877b496dc1f5a0625ca6b0ac1cd11f12f6a/protobuf-3.2.0.tar.gz (132kB)
    100% |████████████████████████████████| 133kB 32.2MB/s 
Collecting six>=1.9 (from protobuf)
  Downloading http://artifactory.west.isilon.com/artifactory/api/pypi/pypi-repo/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz
Requirement already satisfied: setuptools in ./venv-source/lib/python2.7/site-packages (from protobuf)
Installing collected packages: six, protobuf
  Running setup.py install for six ... done
  Running setup.py install for protobuf ... done
Successfully installed protobuf-3.2.0 six-1.10.0
(venv-source)dtucker@dtucker-wkstn:/tmp/pydoofus $ python setup.py build
...
(venv-source)dtucker@dtucker-wkstn:/tmp/pydoofus $ pip install .
...
(venv-source)dtucker@dtucker-wkstn:/tmp/pydoofus $ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydoofus
>>> 
```

**Comment by TeBoring** [comment] 2017-02-17 18:33
Can I see your proto file: RpcPayloadHeader.proto and datatransfer.proto?

**Comment by dmtucker** [comment] 2017-02-17 18:57
@TeBoring They come from Hadoop:
* https://github.com/apache/hadoop/blob/branch-2.0.0-alpha/hadoop-common-project/hadoop-common/src/main/proto/RpcPayloadHeader.proto
* https://github.com/apache/hadoop/blob/branch-2.0.0-alpha/hadoop-hdfs-project/hadoop-hdfs/src/main/proto/datatransfer.proto

(We remove the `option` directives on lines 22-24 and 18-20, respectively.)

**Comment by TeBoring** [comment] 2017-02-17 19:25
I think the pure python implementation has some bug that allow you to define proto enum value with same name. The binary implementation fixed that.
As the log suggests, the SUCCESS in Status and RpcStatusProto all have the same fully qualified name: SUCCESS. I think hadoop should fix that.

**Comment by dmtucker** [comment] 2017-02-17 21:02
@TeBoring FWIW, this is an old version of Hadoop (2.0.0-alpha; for reference, 3.0.0 is now in alpha) that has likely not been updated to work with newer versions of protobuf.

But, regardless, if the bdist fixed a bug, should it not have been released as a new MR (e.g. 3.2.1) instead of as a different dist of the same version? I would never expect an sdist to behave differently than a bdist unless there was a bug in setuptools. Given that [the `cp*` bdists were uploaded 9 days after the sdist](https://pypi.python.org/pypi/protobuf/3.2.0), it seems more likely that the code changed in between builds.

**Comment by dmtucker** [comment] 2017-02-17 21:43
I discussed this with #PyPA a bit on Freenode. It seems like the `cp27` wheel could be using a C extension that has behaviors that differ from the pure-Python implementation of the extension. This does seem to repro with the pure-Python egg and wheel, so perhaps that is the case here?

**Comment by TeBoring** [comment] 2017-02-17 22:06
Instead of saying bdist fixed a bug, it's proper to say there is still a bug in sdist (it should reject duplicate name). Because this bug won't affect correct usage, we won't fix it in a post-release.
I think the problem is that the old version of hadoop doesn't work with protobuf python cpp implementation.
Hadoop should have a new release to fix that, so that it can be used with python cpp implmentation.

**Comment by TeBoring** [comment] 2017-02-17 22:08
BTW, code was not changed between the time we upload bdist and sdist. We used the same commit to create packages.

**Comment by dmtucker** [comment] 2017-02-17 22:51
> Instead of saying bdist fixed a bug, it's proper to say there is still a bug in sdist (it should reject duplicate name).

Fair enough... Is there already an issue tracking that, or should this be that issue?

> Hadoop should have a new release to fix that, so that it can be used with python cpp implmentation.

Like I said, the release in question is ancient. The correct fix from our perspective is to change our protobuf dependency from `>2.5.0` to `~=2.5` so we don't install protobuf 3.x. I filed this because I wasn't sure if this project was already aware of the difference in behavior or not (i.e. the sdist shouldn't work, but it does).

**Comment by TeBoring** [comment] 2017-02-17 23:02
I understand that. Perhaps you can also try avoid using bdist of protobuf.

**Closed** 2018-06-11 20:39 UTC
Labels: obsolete, python
