### ISSUE TITLE
python3  got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by rockyzhengwu** [google/protobuf#4716] opened 2018-06-02 12:52 UTC
use the protobuf in python3 on ubuntu14.04 ,  how to fix this ?
I delete all the serialized_options in the py file and fix this but i can't delete this every time .

```
    import topic_response_pb2
  File "/home/rocky/GitHub/pyemd/test/topic_response_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x1aproto/topic_response.proto\x12\x05topic\"#\n\x05Token\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0c\n\x04prob\x18\x02 \x01(\x01\"E\n\x05Topic\x12\x10\n\x08topic_id\x18\x01 \x01(\x05\x12\x0c\n\x04prob\x18\x02 \x01(\x01\x12\x1c\n\x06tokens\x18\x03 \x03(\x0b\x32\x0c.topic.Token\"Y\n\rTopicResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1c\n\x06tokens\x18\x02 \x03(\x0b\x32\x0c.topic.Token\x12\x1c\n\x06topics\x18\x03 \x03(\x0b\x32\x0c.topic.Topicb\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

```

```
rocky@rocky-ubuntu:~$ protoc --version
libprotoc 3.5.1
rocky@rocky-ubuntu:~$ pip list | grep protobuf
protobuf                           3.5.1 
```

**Comment by davenso** [comment] 2018-06-20 21:04
I am having the same issue.

**Comment by rockyzhengwu** [comment] 2018-06-25 10:11
@davenso I fix this by reinstall python package from source code

**Comment by anandolee** [comment] 2018-07-25 21:52
This error happens when new generated code is being used with an old runtime, That's a configuration we don't support. Upgrade protobuf runtime to newer version later than your protoc version can solve the error.

For compatibility, we support older generated code with newer protobuf runtime.

**Comment by anandolee** [comment] 2018-07-25 22:08
@rockyzhengwu I noticed that your protoc version and protobuf runtime version are both 3.5.1. Thus this error should not happen. I checked the 3.5.1 protoc, serialized_options was not released in that version. 
Can you double check that your /home/rocky/GitHub/pyemd/test/topic_response_pb2.py file is produced by protoc 3.5.1?

**Closed** 2018-08-03 00:27 UTC
Labels: python, question

**Comment by furnlound** [comment] 2018-09-20 18:11
I had the same issue until I realised that checking the pip version with 
`pip show protobuf` 
gives you the python 2 version.
Indeed `pip3 install -U protobuf` did the trick for me.

**Comment by anandolee** [comment] 2018-10-09 18:09
If protoc is newer than runtime, or if using generated _pb2.py code from other libraries(for example Tensorflow) which is using newer protoc version, it may have this problem. Upgrade the runtime to 3.6.0 or above will solve it

**Comment by andrewferlitsch** [comment] 2019-02-17 05:58
FYI> I got this same error when using Google Cloud Vision api. Occur on this line:

# Imports the Google Cloud client library
from google.cloud import vision

The problem went away when I took the above advice of doing:

pip3 install -U protobuf

**Comment by npandey2385** [comment] 2019-03-11 09:36
I am facing the same issue while the version of both  protoc and protobuf module is same

>>> import tensorflow_hub as hub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/grid/common/pkgs/anaconda3/v5.0.1/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 32, in <module>
    from tensorflow_hub.feature_column import image_embedding_column
  File "/grid/common/pkgs/anaconda3/v5.0.1/lib/python3.6/site-packages/tensorflow_hub/feature_column.py", line 24, in <module>
    from tensorflow_hub import image_util
  File "/grid/common/pkgs/anaconda3/v5.0.1/lib/python3.6/site-packages/tensorflow_hub/image_util.py", line 21, in <module>
    from tensorflow_hub import image_module_info_pb2
  File "/grid/common/pkgs/anaconda3/v5.0.1/lib/python3.6/site-packages/tensorflow_hub/image_module_info_pb2.py", line 22, in <module>
    serialized_pb=_b('\n&tensorflow_hub/image_module_info.proto\x12\x0etensorflow_hub\"\x8a\x01\n\x0fImageModuleInfo\x12\x45\n\x12\x64\x65\x66\x61ult_image_size\x18\x01 \x01(\x0b\x32).tensorflow_hub.ImageModuleInfo.InputSize\x1a\x30\n\tInputSize\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05J\x04\x08\x03\x10\x04\x62\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
>>>

$ protoc --version
libprotoc 3.5.1
$ pip list |grep protobuf
protobuf (3.5.1)

**Comment by anandolee** [comment] 2019-03-11 20:18
Tensorflow has shipped some internal generated code (which is using protoc 3.6.0 above, it is not what protoc version you are using) to opensource. Upgrade the runtime to 3.6.0 or above will solve it

**Comment by pipiyang** [comment] 2019-03-15 17:07
When I run tensorflow with protobuf (3.7.0) on Ubuntu 18.04, I had the same problem. Still didn't find a way to fix the problem yet.

**Comment by danintel** [comment] 2019-05-16 23:12
You can either:
1. upgrade to Protobuf 3.6.0 or
2. hand delete the "serialized_options=None," argument from the generated *_pb2.py files.

**Comment by Atlowell** [comment] 2019-10-03 14:12
I am experiencing this issue, I posted an update to #4803

**Comment by grt1st** [comment] 2019-11-11 13:27
> You can either:
> 
> 1. upgrade to Protobuf 3.6.0 or
> 2. hand delete the "serialized_options=None," argument from the generated *_pb2.py files.

Yes, it works. "serialized_options" matters for :
```
    has_options:  True if the descriptor has non-default options.  Usually it
        is not necessary to read this -- just call GetOptions() which will
        happily return the default instance.  However, it's sometimes useful
        for efficiency, and also useful inside the protobuf implementation to
        avoid some bootstrapping issues.
```

Don't know if ok to delete it.

**Comment by Ehsan-Yaghoubi** [comment] 2019-11-20 19:25
In the requirement of the project, it is said to install protobuf 3.5.1, and I got the error. But, when I changed it to the latest version (protobuf 3.10.0), the problem is solved.

**Comment by shazz123** [comment] 2020-06-16 02:19
from sklearn.metrics import roc_auc_score,roc_curve,classification_report
from sklearn.model_selection import cross_val_score
from imblearn.over_sampling import SMOTE
from yellowbrick.classifier import roc_auc


# A function to use smote
def grid_search_random_forrest_best(dataframe,target):
    
    # splitting the data
    x_train,x_val,y_train,y_val = train_test_split(dataframe,target, test_size=0.3, random_state=42)
    
    # Applying Smote on train data for dealing with class imbalance
    smote = SMOTE(kind='regular')
    
    X_sm, y_sm =  smote.fit_sample(x_train, y_train)
    
    rfc = RandomForestClassifier(n_estimators=11, max_features='auto', max_depth=8, criterion='entropy',random_state=42)
    
    rfc.fit(X_sm, y_sm)
    y_pred = rfc.predict(x_val)
    print(classification_report(y_val, y_pred))
    print(confusion_matrix(y_val, y_pred))
    visualizer = roc_auc(rfc,X_sm,y_sm,x_val,y_val)


grid_search_random_forrest_best(X,y)
||
RESULT:
||
TypeError                                 Traceback (most recent call last)
<ipython-input-38-2b8db685c2c0> in <module>
      1 from sklearn.metrics import roc_auc_score,roc_curve,classification_report
      2 from sklearn.model_selection import cross_val_score
----> 3 from imblearn.over_sampling import SMOTE
      4 from yellowbrick.classifier import roc_auc
      5 

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\__init__.py in <module>
     35 from . import ensemble
     36 from . import exceptions
---> 37 from . import keras
     38 from . import metrics
     39 from . import over_sampling

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\keras\__init__.py in <module>
      2 in keras."""
      3 
----> 4 from ._generator import BalancedBatchGenerator
      5 from ._generator import balanced_batch_generator
      6 

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\keras\_generator.py in <module>
     38 
     39 
---> 40 ParentClass, HAS_KERAS = import_keras()
     41 
     42 from scipy.sparse import issparse

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\keras\_generator.py in import_keras()
     28             return tuple(), False
     29 
---> 30     ParentClassKeras, has_keras_k = import_from_keras()
     31     ParentClassTensorflow, has_keras_tf = import_from_tensforflow()
     32     has_keras = has_keras_k or has_keras_tf

C:\ProgramData\Anaconda3\lib\site-packages\imblearn\keras\_generator.py in import_from_keras()
     16     def import_from_keras():
     17         try:
---> 18             import keras
     19             return (keras.utils.Sequence,), True
     20         except ImportError:

C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 from . import losses_utils
      8 from . import metrics_utils

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10 
     11 

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in <module>
      3 from __future__ import print_function
      4 
----> 5 import tensorflow as tf
      6 from tensorflow.python.eager import context
      7 from tensorflow.python.framework import device as tfdev

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     32 
     33 # pylint: disable=g-bad-import-order
---> 34 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     35 from tensorflow.python.tools import module_util as _module_util
     36 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     50 
     51 # Protocol buffers
---> 52 from tensorflow.core.framework.graph_pb2 import *
     53 from tensorflow.core.framework.node_def_pb2 import *
     54 from tensorflow.core.framework.summary_pb2 import *

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\core\framework\graph_pb2.py in <module>
     14 
     15 
---> 16 from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
     17 from tensorflow.core.framework import function_pb2 as tensorflow_dot_core_dot_framework_dot_function__pb2
     18 from tensorflow.core.framework import versions_pb2 as tensorflow_dot_core_dot_framework_dot_versions__pb2

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\core\framework\node_def_pb2.py in <module>
     14 
     15 
---> 16 from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
     17 
     18 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py in <module>
     14 
     15 
---> 16 from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
     17 from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
     18 from tensorflow.core.framework import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\core\framework\tensor_pb2.py in <module>
     14 
     15 
---> 16 from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
     17 from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
     18 from tensorflow.core.framework import types_pb2 as tensorflow_dot_core_dot_framework_dot_types__pb2

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py in <module>
     21   syntax='proto3',
     22   serialized_options=_b('\n\030org.tensorflow.frameworkB\016ResourceHandleP\001Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\370\001\001'),
---> 23   serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
     24 )
     25 

TypeError: __init__() got an unexpected keyword argument 'serialized_options'

**Comment by priteshgohil** [comment] 2020-08-04 19:44
Upgrading protobuf solved my problem
`pip install -U protobuf`

**Comment by Jamie725** [comment] 2021-03-01 01:44
> I had the same issue until I realised that checking the pip version with
> `pip show protobuf`
> gives you the python 2 version.
> Indeed `pip3 install -U protobuf` did the trick for me.

This indeed helped a lot, thanks for sharing this!

**Comment by kuvaldini** [comment] 2021-10-10 21:48
I solved this with `pip install --upgrade protobuf`

(upd) it is already noticed here
