### ISSUE TITLE
protoc v3.5.0 not working as expected 

### ISSUE THREAD

**Issue by athreya92** [google/protobuf#4110] opened 2017-12-28 06:17 UTC
Version 3.3.0
Execution environment: Windows 7
Command: protoc --go_out=. *.proto
Outcome: Proto files are generated

Version 3.5.0
Execution environment: Windows 7
Command: protoc --go_out=. *.proto
Expected Outcome: Proto files must be generated
Issue found: *.proto no such file or directory

For more information, please refer the below link [https://github.com/golang/protobuf/issues/470](url)

**Comment by acozzette** [comment] 2017-12-29 00:23
@athreya92 We rely on the shell to perform filename globbing--`protoc` doesn't attempt to interpret the `*` wildcard but expects the shell to have already replaced it with the matching files. I don't think this could be  bug in `protoc` then. Are you sure that nothing else changed in your environment, like switching to a different shell?

**Comment by athreya92** [comment] 2018-01-02 04:59
@acozzette Thanks for your reply.
The environment was the same with both the versions.

**Comment by pherl** [comment] 2018-01-02 22:09
@laszlocsomor looks like before the long-path support, it does support expanding the wildcasts.

**Comment by paulburlumi** [comment] 2018-01-04 17:07
I can confirm that 3.4.0 also works (on Windows 10), whereas 3.5.1 does not.

**Comment by laszlocsomor** [comment] 2018-02-05 12:33
@pherl : Please see [my comment on #3984](https://github.com/google/protobuf/pull/3984#issuecomment-363071506)

**Comment by xfxyjwf** [comment] 2018-06-25 22:05
Assuming fixed in https://github.com/google/protobuf/pull/3984

**Closed by xfxyjwf** 2018-06-25 22:05 UTC
Labels: bug, c++

**Comment by sneko** [comment] 2018-07-03 20:59
@xfxyjwf I don't understand, it's still not working for me with protoc v3.6.0 😢

**Comment by xfxyjwf** [comment] 2018-07-03 21:02
@sneko Can you create a separate issue listing the steps to reproduce the problem?
