### ISSUE TITLE
3.5.0 fails to build on s390x

### ISSUE THREAD

**Issue by ignatenkobrain** [google/protobuf#3946] opened 2017-11-23 22:51 UTC
```
./.libs/libprotobuf.so: undefined reference to `google::protobuf::internal::Release_CompareAndSwap(long volatile*, long, long)'
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/3169/23323169/build.log

Doesn't seem to happen on any other architecture (even ppc64 succeeds given that it's also Big Endian).

**Comment by pherl** [comment] 2017-11-27 19:00
Duplicate of https://github.com/google/protobuf/issues/2002

Atomicops are supported for each platform explicitly with lots of #ifdef macros. See the second half of the https://github.com/google/protobuf/blob/ccb6b622497c9627898dadcb3818014b3a245d4e/src/google/protobuf/stubs/atomicops.h 

Feel free to send a PR to add s390x support.

**Closed by pherl** 2017-11-27 19:00 UTC
